### ISSUE TITLE
Custom Language adapter for scala not finding "net.fabricmc.api.ModInitializer.<init>()"

### ISSUE THREAD

**Issue by 0xmycf** [QuiltMC/quilt-loader#101]
Hello,

I was making a custom language adapter for scala which I might use in the future (afaik there is no official one yet).
the example mod can be found here: [quilt-template-mod-scala](https://github.com/0xmycf/quilt-template-mod-scala).

Whenever I start the mod outside of IntelliJ I get the following error:

`Caused by: java.lang.NoSuchMethodException: net.fabricmc.api.ModInitializer.<init>()`
[-> The full crashlog <-](https://gist.github.com/0xmycf/80c8b7d9afa30e77112de5868d6d849d)

I do not import anything from the Fabric API anywhere in my code.

I launched Minecraft in version 1.19 with a fresh install of Quilt and the newest version of [Quilted Fabric API (QFAPI) and Quilt Standard Libraries (QSL)](https://modrinth.com/mod/qsl) (qfapi beta.9, qsl beta.16). I do not run any other mods besides those and the [quilt-template-mod-scala](https://github.com/0xmycf/quilt-template-mod-scala).

I don't know if this is a mistake on my part, a QFAPI error or an loader error, so I decided to open the issue here.

Thank you in advance.

**Comment by 0xmycf** [comment]
I realized that I need to make the main class into an object. Which I did. However another error occurred:

`Caused by: java.lang.ClassCastException: class com.example.example_mod.ExampleMod$ cannot be cast to class net.fabricmc.api.ModInitializer (com.example.example_mod.ExampleMod$ is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @613a8ee1; net.fabricmc.api.ModInitializer is in unnamed module of loader 'app')`

Both crashlogs can be found in the link above.

**Comment by AlexIIL** [comment]
Quilt has a different key for it's entrypoints - `init`, rather than fabric's `main`. So the fix would be to change

https://github.com/0xmycf/quilt-template-mod-scala/blob/2fc7d5d50e222f58920caef1b4178ddc26224554/src/main/resources/quilt.mod.json#L25

from `main` to `init`, and then it should work.

**Comment by 0xmycf** [comment]
Thank you, I wasn't aware of this and just assumed its the same... 
The Mod starts now.

Sorry for the inconvenience.
