### ISSUE TITLE
Pls help!

### ISSUE THREAD

**Issue by Suolakissalta** [QuiltMC/quilt-loader#104]
### The game crashed whilst initializing game

**Error: org.quiltmc.loader.impl.entrypoint.QuiltEntrypointException: Exception while loading entries for entrypoint 'client_init' provided by 'quilt_networking'**

Exit Code: -1

[latest.log](https://github.com/QuiltMC/quilt-loader/files/9358980/latest.log)
[crash-2022-08-17_13.58.43-client.txt](https://github.com/QuiltMC/quilt-loader/files/9358981/crash-2022-08-17_13.58.43-client.txt)

**Comment by zOnlyKroks** [comment]
Krypton is somehow causing a crash with the quilt networking API. As a temporary workaround you can remove Krypton.

**Comment by zOnlyKroks** [comment]
Or you try updating Krypton, if there's a new version available.

**Comment by LambdAurora** [comment]
You are using Krypton 0.2.0 which is incompatible with 1.19.1 as networking changes happened, please update to Krypton 0.2.1. I believe this is not a Quilt issue.

**Comment by TheGlitch76** [comment]
This looks like an issue with your mods, not an issue with Quilt. You can get help for support questions like this on either our [forum](https://forum.quiltmc.org/c/support/9) or [Discord server](discord.quiltmc.org).
