### ISSUE TITLE
ClientModInitializer is missing the Deprecated annotation

### ISSUE THREAD

**Issue by Juuxel** [QuiltMC/quilt-loader#109]
https://github.com/QuiltMC/quilt-loader/blob/43d21d02e1271471a659104c3a48e57647f84390/src/fabric/api/java/net/fabricmc/api/ClientModInitializer.java#L32-L35

It only has a note in the javadoc unlike the other `*ModInitializer` interfaces, which also have `@Deprecated` on the interface.

**Comment by AlexIIL** [comment]
Woops, thanks for pointing that out! Fixed in https://github.com/QuiltMC/quilt-loader/commit/9a860efe2894dbbdd990f26bca95a2bf9aad8079
