### ISSUE TITLE
Quilt CTD due to 'No game providers present on the class path!'

### ISSUE THREAD

**Issue by monyarm** [QuiltMC/quilt-loader#112]
Log: https://mclo.gs/xDzktoM
I am running Gentoo Linux, and running Minecraft through PolyMC with Java 17.

This isn't strictly a Linux or PolyMC issue, as both Fabric and Forge lack this issue.

**Comment by DioEgizio** [comment]
can you try on not develop PolyMC?

**Comment by monyarm** [comment]
Ya, using 1.4.1 instead of develop fixed the issue, still not sure what caused it though.

**Comment by DioEgizio** [comment]
It was a polymc bug and it should be fixed. Well, there's a reason why develop isn't recommended to most users
