### ISSUE TITLE
FileSystem reimplementation crashes on Jetbrains SDK

### ISSUE THREAD

**Issue by Pyrofab** [QuiltMC/quilt-loader#113]
Using Jetbrains' JDK with version 17.0.1 causes a NullPointerException when a nested mod gets loaded. This seems to be because this SDK relies on `FileSystemProvider#getFileAttributeView` not returning `null`, which `QuiltMemoryFileSystemProvider` does.

[latest.log](https://gist.github.com/Pyrofab/5c9265a795653452d3ff1f8aec95a5bb)

**Comment by AlexIIL** [comment]
This should be fixed in `0.17.5-beta.2`, can you try updating?

**Comment by Pyrofab** [comment]
Yep, works fine 👍
