### ISSUE TITLE
If a mod is declared as included in the FMJ, but doesn't actually exist, loader crashes

### ISSUE THREAD

**Issue by TropheusJ** [QuiltMC/quilt-loader#116]
If a Jar-in-Jar mod is nested too deep, loader fails to load it.
log:
[latest.log](https://github.com/QuiltMC/quilt-loader/files/9658689/latest.log)
Tested with only [QFAPI](https://modrinth.com/mod/qsl/version/4.0.0-beta.13%2B0.62.0-1.19.2) and [this build of Twilight Forest](https://github.com/QuiltMC/quilt-loader/files/9658709/twilightforest-fabric-1.19.2-4.2.299.jar.zip) on `0.17.5-beta.2`

Twilight Forest includes Porting Lib, which includes all of its modules. `accessors`, the module that crashes it, is 6 layers deep.

**Comment by AlexIIL** [comment]
As far as I can tell the jar is broken. Unfortunately quilt-loader currently does a terrible job of telling you exactly where the problem is, but the problem is`porting-lib-2.0.547+1.19.2.jar` (directly included in `twilightforest-fabric-1.19.2-4.2.299.jar`) names several included jar files (including `accessors-2.0.547+1.19.2.jar`), but it doesn't actually include them. (If they are included in other jars then that's fine, but they shouldn't be listed in jars that they are *not* included in)

**Comment by TropheusJ** [comment]
The nesting is kinda a mess, but all the jars are there. This loads fine on Fabric loader.
`accessors` in particular can be found at Porting Lib -> obj_loader -> model_loader -> extensions -> accessors.

**Comment by AlexIIL** [comment]
Then why are they listed in `porting-lib-2.0.547+1.19.2.jar` if they aren't present in that jar?

In addition, why does `extensions-2.0.547+1.19.2.jar` say it contains 3 jars (`accessors-2.0.547+1.19.2.jar`, `attributes-2.0.547+1.19.2.jar`, and `common-2.0.547+1.19.2.jar)` even though it only contains 2?

**Comment by AlexIIL** [comment]
Fabric loader seems to just ignore missing jar-in-jar entries, which sounds odd to me - if a jar-in-jar is missing then I'd normally assume there's a bug in the build process (or the name has been typed out incorrectly), rather than intended behavior?

**Comment by TropheusJ** [comment]
I see. To minimize jar size, Porting Lib has a task that will deduplicate included jars. This leaves the fmj entries alone though, I should fix that. 
This crash is still different behavior than fabric loader though, and should probably be changed.

**Comment by AlexIIL** [comment]
Okay, quilt-loader should support this as of `0.17.5-beta.3` - can you retest?

**Comment by TropheusJ** [comment]
fixed, it loads now.
