### ISSUE TITLE
Quilt server jar crash due to QSL's Fabric api, log included

### ISSUE THREAD

**Issue by Theslees** [QuiltMC/quilt-loader#118]
[crash-2022-10-03_01.56.39-server.txt](https://github.com/QuiltMC/quilt-loader/files/9694155/crash-2022-10-03_01.56.39-server.txt)

**Comment by TheGlitch76** [comment]
I have a feeling this is due to C2ME, not Quilt. If you can reproduce this error with only QSL, please re-open with specific steps to reproduce.
