### ISSUE TITLE
Minecraft Launcher doesn't open after Quilt crashes

### ISSUE THREAD

**Issue by cootshk** [QuiltMC/quilt-loader#119]
after quilt crashes, the minecraft launcher refuses to open
### temporary solution:
1) open task manager
2) scroll down to background processes
3) find minecraft launcher and hit exit process
4) relaunch the minecraft launcher
5) wait for it to re-authenticate you

**Comment by Gaming32** [comment]
I personally have the launcher set to "keep open". When Quilt crashes, the launcher closes itself. I think it's the same issue, but it has only been happening recently.

**Comment by AlexIIL** [comment]
This is a bug in the launcher, not quilt-loader - especially since this apparently happens when vanilla minecraft crashes.

A fairly similar launcher bug has already been reported to mojang here: https://bugs.mojang.com/browse/MCL-22470
