### ISSUE TITLE
net.fabricmc Namespace Compatibility

### ISSUE THREAD

**Issue by TehcJS** [QuiltMC/quilt-loader#13]
Fabric mods using the `net.fabricmc` namespace cause build and execution issues due to a recent namespace change from `net.fabricmc` to `org.quiltmc`.

**Comment by Prospector** [comment]
Mods should not be touching loader internals

**Comment by chexo3** [comment]
Are there parts of that namespace/package that are reasonable for mods to be using, or at least widely used? You could create a shim namespace with methods that simply call the same function. Would be temporary, of course.

**Comment by TehcJS** [comment]
closed because stale & fixed
