### ISSUE TITLE
Quilt is incompatible with Bewitchment

### ISSUE THREAD

**Issue by kristibektashi** [QuiltMC/quilt-loader#131]
![Error](https://user-images.githubusercontent.com/40217426/197989868-b053854e-3284-4ae6-85ed-220d74568079.png)

**Comment by Fnige** [comment]
Bewitchment depends on a newer version of Pehkui and Patchouli.

Also Quilt loader 0.17.5 (Release, not betas) is what it requires too

**Comment by kristibektashi** [comment]
> Bewitchment depends on a newer version of Pehkui and Patchouli.
> 
> Also Quilt loader 0.17.5 (Release, not betas) is what it requires too

That worked, than you very much.
