### ISSUE TITLE
Server crashes on headless environment

### ISSUE THREAD

**Issue by mooziii** [QuiltMC/quilt-loader#138]
When running the server on a headless environment, it crashes due to no desktop being available.

Logs:
[latest.log](https://pastes.dev/odDo6HWETC)
Quilt Version: 0.18.1-beta.5

I tried to use the `nogui` flag but it didn't work

**Comment by AlexIIL** [comment]
This should be fixed as of https://github.com/QuiltMC/quilt-loader/commit/4e4951221eaaceb1962eaa4297921e7a68326ffd(beta 10) - sorry for not posting about it before!

Please can you retry with beta 12?

**Comment by mooziii** [comment]
works fine
