### ISSUE TITLE
Crash on quilt 0.18.1 - 1.17.6 works fine on this modpack, no idea why, but figured i'd report anyway

### ISSUE THREAD

**Issue by netcore10** [QuiltMC/quilt-loader#141]
https://mclo.gs/9RlMQP8

**Comment by AlexIIL** [comment]
It looks like the mod MixinConflictHelper's forked process crashed before it could receive the mod information - unfortunately the reason why it crashed is not in the log, but instead will only be in the "minecraft log" of your launcher - can you try to re-run, and see if there's any error messages in there?

**Comment by AlexIIL** [comment]
To be honest though I guess the problem is here: https://github.com/isXander/MixinConflictHelper/blob/1.19/src/main/java/dev/isxander/mixinconflicthelper/gui/SwingForkHelper.java#L40 since that's the only code that interacts with quilt loader.

**Comment by netcore10** [comment]
I removed mixin helper and still crash.

**Comment by OroArmor** [comment]
Looks like an issue with CCA and requiem

**Comment by netcore10** [comment]
CCA?

**Comment by OroArmor** [comment]
Cardinal components api. Requiem is calling that api but not doing so correctly

**Comment by netcore10** [comment]
no idea why it works on an older quilt then.

**Comment by OroArmor** [comment]
Oh. Thats a problem :/

**Comment by netcore10** [comment]
yeah, it had me confused when i updated. Glad i didn't update my server yet.

**Comment by netcore10** [comment]
Any news on why a modpack that was working on 17.6 launcher might not work on 18.1 launcher?

**Comment by netcore10** [comment]
Fixed on My client with latest beta now!
