### ISSUE TITLE
0.18.1 breaks Charm, CCA

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#142]
Tested my modpack against Quilt loader 0.18.1, found out the following:

- [Charm](https://www.curseforge.com/minecraft/mc-mods/charm) causes a crash on startup. This crash also fails to open Quilt's new crash window and the crash log it generates is standard.
- Any mod, that uses [Cardinal Components API](https://www.curseforge.com/minecraft/mc-mods/cardinal-components/relations/dependents?filter-related-dependents=1) (not on the list: [Fat Chicken](https://www.curseforge.com/minecraft/mc-mods/fat-chicken), [Utility Belt](https://www.curseforge.com/minecraft/mc-mods/utility-belt)), causes a crash on startup, related: https://github.com/QuiltMC/quilt-loader/issues/141.

The rest of the mods seem to work fine. The crash reporter looks great, but hopefully the loading times will be brought back down to acceptable levels (the initialization process alone went from seconds to 3min).

Logs for the Charm crash: https://gist.github.com/SplendidAlakey/62049b5306eba80c7f96578de8deb750

**Comment by AlexIIL** [comment]
Thanks! Charm looks like it might be a bit more difficult for us to fix, but the CCA bug should be fixed in `0.18.1-beta.9`

> (the initialization process alone went from seconds to 3min).

That's... not ideal. I've done a little bit of profiling and I'm not sure if I should blame `QuiltMemoryFileSystemProvider.newInputStream` or the classpath that tries to find resources from each one. Either way I'll look into it more, since 3 mins is a lot worse than I initially expected it to be.

**Comment by SplendidAlakey** [comment]
Alright, just tested beta 9, all CCA mods load without issues now, thanks.

I was now able to load my entire modpack, apart from Charm and YUNG's mods, and noted the times:

- just about 1min before the debug success screen appears
- 5min after that before MC window appears
- no change in loading times for MC itself (which is at most 4min for my pack)

That's roughly 5.5min increase in comparison to 0.17.6.

**Comment by AlexIIL** [comment]
I think beta.20 should have fixed charm, can you retry?

**Comment by SplendidAlakey** [comment]
Will try as soon as Prism catches up. So far only 19 is available.

**Comment by AlexIIL** [comment]
Thanks!

Technically you could try adding `-Dloader.workaround.jar_copied_mods=charm`, since beta.20 just adds charm to that list

**Comment by SplendidAlakey** [comment]
Worked, thanks a lot! All the problems I had with 0.18.x are fixed.
