### ISSUE TITLE
Add a config option to skip the mod loading state window

### ISSUE THREAD

**Issue by anonymous123-code** [QuiltMC/quilt-loader#144]
This would allow users to launch skipping the mod loading state popup.

**Comment by AlexIIL** [comment]
To be honest I'm not sure why I forced it to always show... but it was a bad idea. I'm adding a config option to *enable* it (so it won't show by default - unless there are warnings *and* it's running in a development environment)

**Comment by TheGlitch76** [comment]
Exists as of `0.18`
