### ISSUE TITLE
Latest Qfapi crashes my client, it worked on the one prior, any chance you know what the problem is so i can relay to the right mod?

### ISSUE THREAD

**Issue by netcore10** [QuiltMC/quilt-loader#149]
https://paste.atlauncher.com/view/a63d699b-5edc-4022-9ea3-40017edb7dbb

**Comment by triphora** [comment]
Requiem.

In the future, please don't use the issue trackers for support: https://discord.quiltmc.org

**Comment by netcore10** [comment]
Apologies!
