### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ghost** [QuiltMC/quilt-loader#153]
[crash-2022-11-19_19.54.27.2915-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10046895/crash-2022-11-19_19.54.27.2915-quilt_loader.txt)

**Comment by TheGlitch76** [comment]
This looks like an issue with your mods, not an issue with Quilt Loader. You can get help for support questions like this on either our [forum](https://forum.quiltmc.org/c/support/9) or [Discord server](discord.quiltmc.org).
