### ISSUE TITLE
QuiltBasePath bug with ..

### ISSUE THREAD

**Issue by TheEpicBlock** [QuiltMC/quilt-loader#157]
`QuiltBasePath`'s `normalize` function doesn't handle multiple `..`'s in a row properly. Example: `/data/fabric_dimension/dimension_type/../../../../../../resources/testmod/data/fabric_dimension/dimension_type/void_type.json` normalizes to `/data/fabric_dimension/dimension_type/resources/testmod/data/fabric_dimension/dimension_type/void_type.json`. This is because of the order in which they're resolved (from right to left), which causes the `..`'s to climb up themselves instead of the right folder.

As of right now I don't think anything is actually making use of this, but it's a bug nonetheless

**Comment by AlexIIL** [comment]
Yeah this is definitely wrong :p

**Comment by TheGlitch76** [comment]
Fixed with https://github.com/QuiltMC/quilt-loader/commit/7bbafa52a138ef47e98ccb7dc999f776d75f3e96
