### ISSUE TITLE
Idk what happend

### ISSUE THREAD

**Issue by SquaredHedghehog** [QuiltMC/quilt-loader#159]
Idk what happend but i cant play minecraft on quilt

<img width="583" alt="Screenshot 2022-11-26 113653" src="https://user-images.githubusercontent.com/87670278/204082216-233fac9f-6d96-49f7-8b78-a583d08ee092.png">
 
[crash-2022-11-26_11.36.00.2120-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10095995/crash-2022-11-26_11.36.00.2120-quilt_loader.txt)

**Comment by AlexIIL** [comment]
It looks like you've accidentally downloaded the development version of smooth-chunks, rather than the normal version? (Try downloading `smooth-chunks-1.0.0.jar` and deleting `smooth-chunks-1.0.0-dev.jar`)

**Comment by AlexIIL** [comment]
Oh, it looks like that version of smooth chunks is for 1.16.x, not 1.19 - try using https://modrinth.com/mod/animated-chunks instead?

**Comment by SquaredHedghehog** [comment]
> Oh, it looks like that version of smooth chunks is for 1.16.x, not 1.19 - try using https://modrinth.com/mod/animated-chunks instead?

didnt worked

**Comment by AlexIIL** [comment]
Ah, sadly I think it might be incompatible with sodium - so you might have to remove it instead.

**Comment by Gaming32** [comment]
Smooth Chunks is also incompatible with Sodium

**Comment by SquaredHedghehog** [comment]
i removed smooth chunks and i still cant open minecraft

**Comment by SquaredHedghehog** [comment]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/87670278/204083107-efa8fea8-a1e4-4f0f-8831-61881d8bf797.png">

i cant even reinstall quilt
(the .jar version isnt working to)

**Comment by SquaredHedghehog** [comment]
and if i am launching quilt with any mod (only one)
the quilt launcher tells me that the mod requires fabric/quilt wich is missing
BuT I LUncUinG IT ThROuGH QuILT

**Comment by Gaming32** [comment]
If it says that fabric is missing, that's referring to Fabric API. So go install [QFAPI/QSL](https://modrinth.com/mod/qsl).

**Comment by SquaredHedghehog** [comment]
didnt worked to
