### ISSUE TITLE
Charm crash on server startup. 0.18.1 Beta 20

### ISSUE THREAD

**Issue by waddon1** [QuiltMC/quilt-loader#163]
I'm aware that Charm was fixed as of 0.18.1 Beta 20 of Quilt. Whilst it now works on my client it does not launch on the server.

[crash-2022-12-02_02.14.09.8427-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10137611/crash-2022-12-02_02.14.09.8427-quilt_loader.txt)

**Comment by AlexIIL** [comment]
Thanks for reporting - it looks like something has gone wrong while quilt-loader performed dependency resolution, rather than a specific problem with charm.

**Comment by AlexIIL** [comment]
Okay beta 21 should fix this - can you retry?

**Comment by waddon1** [comment]
Just tried it and it seems to work now thanks
