### ISSUE TITLE
Fabric API on QL 0.18.1-beta.21 breaks the title screen panorama

### ISSUE THREAD

**Issue by Ampflower** [QuiltMC/quilt-loader#164]
When loading Fabric API as-is on Quilt, the title screen panorama unexpectedly breaks.

## Steps to Reproduce
 - Install Quilt Loader 0.18.1-beta.21 with Minecraft 1.19.2
   - Other versions may work
 - Install Fabric API 0.68.0+1.19.2
 - Launch the game

## Expected Results
The game to function as normal

## Actual Results
Something with resource loading breaks the panorama.

**Comment by AlexIIL** [comment]
Thanks for the report! It looks like beta 5 was the last version that this worked on, and beta 7 broke it (there was no beta 6).

**Comment by AlexIIL** [comment]
It looks like the panoramas are in *two* places: once in the minecraft jar (but only the first 85 bytes) and again in the "asset index" - which means they are a separate download from the original jar. I think this means quilt-loader will need to delete the duplicate files from the minecraft jar when it performs remapping, or when loading the minecraft jar as a resource.

**Comment by AlexIIL** [comment]
Oh, and as of beta 7 quilt-loader exposes the minecraft jar through it's mod container, which means fabric probably searches for it first in resource packs?

**Comment by kb-1000** [comment]
The panorama files inside the JAR are a fallback should the external assets be missing, Minecraft can run completely fine without the assets present (minus that sounds, window icons, translations and the panoramas will be missing, but it won't crash). If you now remove these files from the JAR completely (or filter them out in another way), you're changing that behavior.
The actual issue that you'd need to fix somehow is the resource pack order (or what resource pack these two are part of), not that these assets are present inside the JAR at all, the external assets should have priority.
It's worth noting that such a targeted hack will also not solve any other issues this may cause (what if Mojang wants to override other bundled resources? as far as I'm aware they've done splash texts in the past, for example)

**Comment by AlexIIL** [comment]
Yeah, that's a good point. I suppose I'll need to look more closely at how fabric api determines how resource packs should be sourced, since I probably broke something about that in the past.

**Comment by AlexIIL** [comment]
It looks like all builtin mods return `quilt` from `FabricModMetadata.getType()`, which is probably the cause of the bug.

**Comment by Ampflower** [comment]
Oh, yeah, should say: Theoretical fix does seem to work for Fabric API 0.68.0+1.19.2 on Loader 0.18.1-beta.23.

**Comment by AlexIIL** [comment]
Thanks for rechecking!
