### ISSUE TITLE
Charm causes many other mods to not function

### ISSUE THREAD

**Issue by RWRmrfrog** [QuiltMC/quilt-loader#166]
Without charm, all the mods run perfectly on quilt. With charm, client crashes on startup. This does not happen on fabric. 
[crash-2022-12-06_18.40.18-client.txt](https://github.com/QuiltMC/quilt-loader/files/10171276/crash-2022-12-06_18.40.18-client.txt)

**Comment by TheGlitch76** [comment]
This looks like an issue with your mods, not an issue with Quilt. You can get help for support questions like this one on either our [forum](https://forum.quiltmc.org/c/support/9) or [Discord server](discord.quiltmc.org).
