### ISSUE TITLE
Something went very very wrong

### ISSUE THREAD

**Issue by Teraunce** [QuiltMC/quilt-loader#167]
It told me to post https://mclo.gs/pqjqWmA here.

**Comment by AlexIIL** [comment]
Thanks for the report! I think the issue here is that you're got the `1.18.2` version of `Oh The Biomes You'll Go`, when you actually need the `1.19.2` version - try this file instead? https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/4027262

**Comment by Teraunce** [comment]
> Thanks for the report! I think the issue here is that you're got the `1.18.2` version of `Oh The Biomes You'll Go`, when you actually need the `1.19.2` version - try this file instead? https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/4027262

fixed that. Then I got https://mclo.gs/YPndIYv

**Comment by TheGlitch76** [comment]
Closing this. You can get help for support questions like this one on either our [forum](https://forum.quiltmc.org/c/support/9) or [Discord server](discord.quiltmc.org).
