### ISSUE TITLE
0.17.7 fails to load some recipes

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#169]
Noticed, when updating my modpack from 0.17.6 to 0.17.7. I'm not sure how much exactly does the issue affect, but you can test it with Create by trying to craft sandpaper: https://github.com/Fabricators-of-Create/Create/issues/665.

0.18.x doesn't have that issue, so, if it's planned to release soon, I suppose there's no point updating 0.17.x to fix this.

**Comment by AlexIIL** [comment]
That's very odd, since 0.17.7 didn't add very much - only ignoring mappings (https://github.com/QuiltMC/quilt-loader/commit/4b4a2d78f658e3c0450866cd38b1732de540215c) and [`CachedFileSystem`](https://github.com/QuiltMC/quilt-loader/commit/c5379ec8dba35d3f192852528fe200cf8e6489d9): a new interface for filesystems (which isn't called anywhere)

**Comment by AlexIIL** [comment]
I can't reproduce this with quilt-loader 0.17.7, `qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2.jar`, and `create-fabric-0.5.0g-796+1.19.2.jar` - are you using different versions?

**Comment by SplendidAlakey** [comment]
Ehm... odd. I'm no longer able to reproduce this. Sorry, I really don't know what's up, but I tested it several times and changing between 0.17.7 and 0.18.1-beta.23 was what solved it. I will reopen this, if I can reliably reproduce it again.

**Comment by SplendidAlakey** [comment]
The original reporter replied, that downgrading to 0.17.7 causes the issue to reappear, whereas upgrading to 0.18.x fixes it: https://github.com/Fabricators-of-Create/Create/issues/665#issuecomment-1344757509. That's exactly what happened to me until.. it just didn't. I still have no way to reliably reproduce it, though.

**Comment by EzioisAwesome56** [comment]
> I can't reproduce this with quilt-loader 0.17.7, `qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2.jar`, and `create-fabric-0.5.0g-796+1.19.2.jar` - are you using different versions?

dunno how but i am still able to reproduce on 1.17.7 and beta 24 of QFA, even after a quick upgrade to the newest quilt loader version and then going back to 1.17.7
![image](https://user-images.githubusercontent.com/21185626/206793436-16173fd1-239d-43c3-b196-3ab0cbc77c9e.png)
![image](https://user-images.githubusercontent.com/21185626/206793470-d7bde9a3-9810-407b-a1d6-81ed3de8eebe.png)
![image](https://user-images.githubusercontent.com/21185626/206793495-219b7c9b-5d50-4f9a-bf8a-a17f86444fa1.png)

i am running the game with a ton of other mods at the moment tho

EDIT: however, my instance with basically 0 mods can sometimes reproduce, ive gotten a launch where it works and a launch where it doesnt.
![image](https://user-images.githubusercontent.com/21185626/206793933-37e6318a-a373-44b8-9603-c1d259fc1ed7.png)
![image](https://user-images.githubusercontent.com/21185626/206794118-57360814-4842-4147-8d06-1e35bcc76c0e.png)
(course now it wont launch with it working)

**Comment by SplendidAlakey** [comment]
When I tried it, I could reproduce it on both a fresh instance and a massive modpack. Now, I can't reproduce it with a fresh one and honestly too lazy to reinstall the old one to test. I can say with a 100% certainty only that it can be reproduced on a fresh instance and that logs don't show any errors at all.

And yeah, I see that you now also can't reliably reproduce it anymore on a fresh instance, either.

**Comment by EzioisAwesome56** [comment]
> And yeah, I see that you now also can't reliably reproduce it anymore on a fresh instance, either.

actually i have more issues  making it work correctly then not rn, but its w/e

**Comment by SplendidAlakey** [comment]
Another user has reported having this issue on 0.18.x-beta.27 https://github.com/Fabricators-of-Create/Create/issues/665#issuecomment-1379659066. Might not be a Quilt issue after all.

**Comment by eristhea** [comment]
appears to be fixed (https://github.com/Fabricators-of-Create/Create/issues/665#issuecomment-1413260966)

**Comment by SplendidAlakey** [comment]
I didn't test it myself, but appears to be fixed. If anyone experiences it again - open a new issue.
