### ISSUE TITLE
Minecraft crashes on launch with Prism Launcher (Version 5.2) and Quilt (Version 0.18.1-beta23); Crash report attached

### ISSUE THREAD

**Issue by roxithegremlin** [QuiltMC/quilt-loader#170]
Mods are listed in crash report
[crash-2022-12-10_23.26.56.4500-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10201067/crash-2022-12-10_23.26.56.4500-quilt_loader.txt)

**Comment by AlexIIL** [comment]
It looks like you're downloaded the fabric version of mcwifipnp - try the quilt version instead?

**Comment by roxithegremlin** [comment]
thank you
