### ISSUE TITLE
Confusing error message when you have both Quilt Kotlin and Fabric Kotlin

### ISSUE THREAD

**Issue by berserkuxyside** [QuiltMC/quilt-loader#171]
[crash-2022-12-11_03.23.13.2048-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10201172/crash-2022-12-11_03.23.13.2048-quilt_loader.txt)

**Comment by AlexIIL** [comment]
It looks like you have both `Quilt Kotlin Libraries` and `Fabric Language Kotlin` - however `Fabric Language Kotlin` is provided by  `Quilt Kotlin Libraries`, so you should remove `Fabric Language Kotlin`.

**Comment by AlexIIL** [comment]
Thanks for reporting this though - I'll need to improve how loader displays these sort of errors in the future.

**Comment by TheGlitch76** [comment]
See #309
