### ISSUE TITLE
Failed to launch on modded Minecraft 1.19.3 with loader 0.18.1.beta.23

### ISSUE THREAD

**Issue by arenekosreal** [QuiltMC/quilt-loader#172]
This is the crash report:

[crash-2022-12-11_15.22.23.5391-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10201680/crash-2022-12-11_15.22.23.5391-quilt_loader.txt)

It seems that the Fabric Loader provided by Quilt Loader is not new enough for those Fabric mods.

**Comment by Gaming32** [comment]
This isn't just a 1.19.3 issue. It also affected my 1.19.2 mod.

**Comment by byquanton** [comment]
It is fixed in 302d8d7. You can either "downgrade" the fabric-loader version in the mods fabric.mod.json file, or wait till the next build is released.

**Comment by arenekosreal** [comment]
Ah, thanks for your help, I have not checked the commits list so I does not notice about it
