### ISSUE TITLE
Missing 0.14.11 of fabricloader in Quilt Loader 0.18.1-beta.23

### ISSUE THREAD

**Issue by emielderckx** [QuiltMC/quilt-loader#174]
Multiple mods require fabricloader 0.14.11 that is not available in Quilt Loader 0.18.1-beta.23 for example Logical Zoom, Purpur Client and more.

`requires version [[0.14.11,∞)] of fabricloader, but only a different version is present: 0.14.10`

crash report:
https://mcpaste.io/ed9052fa528a93a1

**Comment by slushie0** [comment]
Am having this issue as well

**Comment by emielderckx** [comment]
> Am having this issue as well

Update your Quilt loader (it's fixed in 0.18.1-beta.25)
