### ISSUE TITLE
internal error!

### ISSUE THREAD

**Issue by RegulusSource** [QuiltMC/quilt-loader#178]
[crash-2022-12-14_21.10.42.6196-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10228063/crash-2022-12-14_21.10.42.6196-quilt_loader.txt)

**Comment by Leo40Git** [comment]
\>`java.lang.ClassNotFoundException: java.util.Map`
...it couldn't find a standard Java library class, oh dear

What version of Java are you using and where did you install it from?

**Comment by AlexIIL** [comment]
That's not the problem, although I haven't looked into what could cause this yet.

**Comment by byquanton** [comment]
Using Java 20? Maybe try using a stable JVM and not some Early-Access Build ...
