### ISSUE TITLE
Crash on startup with CraftTweaker on 0.18.x

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#179]
**MC** 1.19.2
**QFAPI** 4.0.0-beta.24
**Quilt Loader** 0.18.1-beta.23
**[CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)** 10.0.23

`-Dloader.workaround.jar_copied_mods=crafttweaker` workaround works.

Logs: https://gist.github.com/SplendidAlakey/9f77b2bcfb167a67b2b56c2b85d3b961

**Comment by AlexIIL** [comment]
All mods that use `reflections` are broken apparently

**Comment by AlexIIL** [comment]
Okay this should be fixed in beta 79, can you recheck?

**Comment by SplendidAlakey** [comment]
Yep, it works with beta 79.
