### ISSUE TITLE
crashes at launch

### ISSUE THREAD

**Issue by Sujeitom** [QuiltMC/quilt-loader#181]
[crash-2022-12-24_12.24.54.9828-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10298372/crash-2022-12-24_12.24.54.9828-quilt_loader.txt)

**Comment by byquanton** [comment]
@Sujeitom Either use Phosphor or Starlight.
![image](https://user-images.githubusercontent.com/32410361/209443578-98fbe6e1-9152-481b-b522-031e87787edb.png)

https://modrinth.com/mod/starlight

**Comment by CheaterCodes** [comment]
Hi, please ask support questions in the [forum](forum.quiltmc.org) or in [discord](discord.quiltmc.org).
Thanks!
