### ISSUE TITLE
crash at launch

### ISSUE THREAD

**Issue by hohlovskrivalka** [QuiltMC/quilt-loader#182]
[crash-2022-12-27_02.22.15.7015-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10305005/crash-2022-12-27_02.22.15.7015-quilt_loader.txt)
[crash-2022-12-27_02.27.05-client.txt](https://github.com/QuiltMC/quilt-loader/files/10305006/crash-2022-12-27_02.27.05-client.txt)
[latest.log](https://github.com/QuiltMC/quilt-loader/files/10305008/latest.log)

**Comment by CheaterCodes** [comment]
Hi, please ask support questions in the [forum](forum.quiltmc.org) or in [discord](discord.quiltmc.org).
Thanks!
