### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by jucogjucogi** [QuiltMC/quilt-loader#187]
installed a bunch of mods and game crashes. 
[crash-2023-01-03_14.10.33-client.txt](https://github.com/QuiltMC/quilt-loader/files/10336110/crash-2023-01-03_14.10.33-client.txt)
mods in crash report. ask for other logs if needed.

**Comment by DanMeadWasTaken** [comment]
Well, I'm not the devs- but i can see in the log that it states multiple... and i mean like a good 10-20 times that sodium-extra is not applying a mixin correctly, so try removing that mod or disabling it and show what ya get after that if ya get a crash.

**Comment by TheGlitch76** [comment]
This looks like an issue with your mods, not an issue with Quilt. You can get help for support questions like this one on either our [forum](https://forum.quiltmc.org/c/support/9) or [Discord server](discord.quiltmc.org).
