### ISSUE TITLE
quilt-loader-0.18.1-beta.29 spams something about "Found access to quilt-loader internal interface"

### ISSUE THREAD

**Issue by Mg138** [QuiltMC/quilt-loader#196]
We have quite literally no idea what's going on. Fresh install via quilt-installer-0.5.0.

latest.log: http://0x0.st/o7ps.log

**Comment by AlexIIL** [comment]
It looks like loader's internal hiding PR (#161) interacts poorly with log4j - for now you'll need to dowgrade to beta 28 (using the same installation process).

**Comment by Ahptt** [comment]
Can also confirm that this occurs when attempting to run Quilt via docker. I will downgrade from the latest quilt for the time being.

**Comment by AlexIIL** [comment]
Okay, I've disabled that new functionality in beta 30, so it should work now.

**Comment by AlexIIL** [comment]
And I've re-enabled it but fixed the broken functionality in beta 34 - so this should be fixed now?

**Comment by Mg138** [comment]
We will close this for now, we're not in a position to test it yet, but we think it should be fine. Will reopen if it still doesn't work.
