### ISSUE TITLE
Significantly slower ModMenu processing on 0.18.x betas compared to 0.17.8

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#198]
**MC** 1.19.2
**Quilt Loader** 0.18.x

Not sure exactly which version introduced the slowdown (at least beta 27 and above, but probably earlier), I don't recall noticing it before, but right now, whenever I open mod menu on 0.18.x, I get a 26sec stutter before it opens, as opposed to just 6sec on 0.17.8 (in a modpack, I'm not sure you would notice the difference with just a few mods or no mods at all). I've been investigating this issue for a while, trying all sorts of settings in ModMenu itself, compact mode, hiding unnecessary mods/libraries, etc, but it turned out to be caused by QL 0.18.x, as 0.17.x doesn't have the same issue.

Again, not sure if logs are going to be of any use:

0.17.8: https://gist.github.com/SplendidAlakey/c90e9a25b7dcc72d79440eee314e5be0#file-stable_latest-log (38:06 mark is when I click on mod menu, 38:12 is when it opens)
0.18.1-beta.28: https://gist.github.com/SplendidAlakey/c90e9a25b7dcc72d79440eee314e5be0#file-beta_latest-log (28:15 mark is when I click on mod menu, 28:41 is when it opens)

Edit: just tried practically the same pack on Fabric and it only takes 2sec to open mod menu, so something on Quilt's side is slowing it down in general.

**Comment by AlexIIL** [comment]
Can you try [creating a profiler snapshot](https://github.com/QuiltMC/quilt-loader/issues/197#issuecomment-1381022936) in the same way as you did before, but this time only starting the profiler before you click on the "Mods" button and stopping the profiler after the window opens? That way we can see what part of quilt is causing the problem.

**Comment by SplendidAlakey** [comment]
There you go: [removed]

**Comment by AlexIIL** [comment]
Thanks! It looks like it's spending a lot of time converting quilt metadata to fabric metadata, so I'll cache that.

**Comment by SplendidAlakey** [comment]
Completely fixed on beta 41, thank you! Now takes only 2sec to open the mod menu, just like on Fabric.
