### ISSUE TITLE
Fail to launch because fabric-loader 0.14.12 not available

### ISSUE THREAD

**Issue by Sammcb** [QuiltMC/quilt-loader#199]
Game fails to launch because on of the mods I have installed requires `fabric-loader 0.14.12`. This appears to not be included in the 0.17.8 version of the quilt-loader. Just curious if there is an ETA on when the new fabric-loader version will be included.

I'm running quilt-loader 0.17.8 for 1.19.2.

Thanks!

**Comment by AlexIIL** [comment]
Quilt Loader 1.17.10 now provides `fabric-loader 0.14.12`, so this should work now?

**Comment by Sammcb** [comment]
Thanks!
