### ISSUE TITLE
Error after updating beta32

### ISSUE THREAD

**Issue by RegulusSource** [QuiltMC/quilt-loader#212]
The original version is beta30, but will not start when it is updated to 0.18.1beta32
[crash-2023-01-22_24.12.43.2702-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10472546/crash-2023-01-22_24.12.43.2702-quilt_loader.txt)

**Comment by SplendidAlakey** [comment]
Beta 53 is currently the latest, try updating to that one. Your specific crash has been fixed a while ago.

**Comment by RegulusSource** [comment]
The problem was fixed, but I found it in the updated 1.19.3 release
[crash-2023-01-22_16.02.32-client.txt](https://github.com/QuiltMC/quilt-loader/files/10473977/crash-2023-01-22_16.02.32-client.txt)
