### ISSUE TITLE
"Couldn't retrieve client jar!" error with Polymer

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#213]
**MC** 1.19.2
**QL** 0.18.1-beta.53
**[Polymer](https://www.curseforge.com/minecraft/mc-mods/polymer)** 0.2.24

There don't seem to be any issues, at a first glance, however I'm consistently getting the "Couldn't retrieve client jar!" error when using Polymer with the latest betas of QL. Sounds critical, so reporting, just in case.

Logs: https://gist.github.com/SplendidAlakey/62cf4ee501153cb6a821f2da2d62f3b9

**Comment by AlexIIL** [comment]
It looks like the error goes away if I add `minecraft` to the list of jar-copied mods in 1.19.2, or if I use any version of polymer for 1.19.3 - so I'll add a rule to make polymer automatically copy minecraft if it's `<=1.19.2`

**Comment by Patbox** [comment]
This issue will happen on 1.19.3 with `polymer-resource-pack` module! Btw next time please also report quilt issues to me so I can fix them where possible

**Comment by SplendidAlakey** [comment]
> Btw next time please also report quilt issues to me so I can fix them where possible

Alright, will do. I just reported it here first, since it was caused by one of the QL betas, rather than the mod.

**Comment by SplendidAlakey** [comment]
Seems to be fixed in beta 59, not seeing any errors now.
