### ISSUE TITLE
Cannot start after being replaced with quilt

### ISSUE THREAD

**Issue by RegulusSource** [QuiltMC/quilt-loader#216]
I changed the quilt loader because I added several quilt mod, but it couldn't start
[crash-2023-01-22_16.02.32-client.txt](https://github.com/QuiltMC/quilt-loader/files/10474070/crash-2023-01-22_16.02.32-client.txt)

**Comment by TheGlitch76** [comment]
This looks like an issue with your mods, not an issue with Quilt Loader. You can get help for support questions like this on either our [forum](https://forum.quiltmc.org/c/support/9) or [Discord server](discord.quiltmc.org).
