### ISSUE TITLE
FAPI crashes on beta 58 and above

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#217]
**MC** 1.19.2
**FAPI** 0.73.0

While most Quilt users will/should use QSL, some will not and instead rely on JiJ'd modules the mods supply, e.g. Sodium and Iris combo.

On beta 58 and above having any FAPI modules results in `Failed to locate Minecraft assets root!` crash.

Logs: https://gist.github.com/SplendidAlakey/f44549d5a5a08825de9e54380f97538d

**Comment by TheGlitch76** [comment]
This issue does not seem to affect 1.19.3

**Comment by SplendidAlakey** [comment]
Fixed in beta 74.
