### ISSUE TITLE
Autogenerate the `quilt-installer(.launchwrapper).json` files

### ISSUE THREAD

**Issue by i509VCB** [QuiltMC/quilt-loader#22]
The last few updates to loader and it's dependencies, I've noticed we haven't updated the entries in those files. We should consider auto generating this using gradle's own dependency resolution. We can do things such as launchwrapper specific dependencies via a custom configuration if needed.

**Comment by TheGlitch76** [comment]
https://github.com/QuiltMC/quilt-loader/pull/120
