### ISSUE TITLE
Crash on dedicated servers below 1.18 with Beta 59

### ISSUE THREAD

**Issue by JulianVennen** [QuiltMC/quilt-loader#223]
1.14.4-1.17.1 crash with the latest quilt beta.

Example log from 1.17.1: https://mclo.gs/XG34DIt
[1.16.5](https://mclo.gs/t9JyDNg), [1.15.2](https://mclo.gs/8gTCg8B) and [1.14.4](https://mclo.gs/3OReAuH) show the same error

**Comment by AlexIIL** [comment]
Okay, this should be fixed as of beta 60 - can you retry?

**Comment by JulianVennen** [comment]
yup, that worked
