### ISSUE TITLE
Previous transform cache is never re-used

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#225]
This is somewhat of a continuation of #197, because it has to do with loading times. After my last test, which was perfect and resulted in 2min of pre game loading and 4min15sec of game loading, I updated some mods and started experiencing 2min30sec and 5min15sec loading times instead. At first, I chalked it up to me updating the mods, but the issue did not go away. I'm consistently getting slower loading times, no matter what I do.

Here's a snapshot of an instance, that was launched twice, prior to making it: [snapshot_beta60.zip](https://github.com/QuiltMC/quilt-loader/files/10518528/snapshot_beta60.zip)

Here's the latest.log, just in case: https://gist.github.com/SplendidAlakey/ffd610065e9336cdd38752f5d16ebbc8

Logs always mention not re-using the previous transform cache, despite nothing changing, so I'm suspecting this is why I'm experiencing the slowdown.

**Comment by AlexIIL** [comment]
Nothing may be changing in the mods folder, but it looks like the order of mods is still changing anyway. This is probably caused by us relying on the order a HashMap stores mods in which... isn't ideal. (And clearly not working very well). I think I can fix this by explicitly sorting the mods, and then shuffling them in a constant manor.

~~I've also realized another optimization I can do - currently 14 seconds is spent reading and decompressing zip file entries when storing them in memory - but that's somewhat unnecessary, since we should be able to just store the pre-compressed file entries in-memory instead, and decompress them as needed. (This last step might not actually happen if the transform cache is being used).~~ Edit: I don't actually think that will work. Oh well.

**Comment by AlexIIL** [comment]
Okay, this should be fixed in beta 63. This also moves "copied jars" to the transform cache *folder*, rather than being temporary files that are copied every run. That should save some time too hopefully :P

**Comment by SplendidAlakey** [comment]
Polymer + Frame API combo crashes on startup with beta 63: https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-frame_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-frame_latest-log

Copying workaround now seems to not work, because it causes Charm to crash on startup (and I assume YUNG's mods will crash on worldgen): https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-charm_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-charm_latest-log

Snapshot from beta 62, 2min5sec + 4min40sec: [snapshot_beta62.zip](https://github.com/QuiltMC/quilt-loader/files/10527778/snapshot_beta62.zip)

Snapshot of the same exact instance, except this time it took 2min5sec + 4min50sec: [snapshot_beta62_slower.zip](https://github.com/QuiltMC/quilt-loader/files/10527831/snapshot_beta62_slower.zip)

Edit: managed to get a snapshot of a loading, that took 2min30sec + almost exactly 5min: [snapshot_beta62_slowest.zip](https://github.com/QuiltMC/quilt-loader/files/10528520/snapshot_beta62_slowest.zip). What stands out about this one is that Log Begone failed to work again... Could be causing slower loading due to much more stuff being logged, but by this much? Not sure.

Edit2: managed to get a really slow one, 2min30sec + 5min30sec, dead log filtering: [snapshot_beta62_slowest_2.zip](https://github.com/QuiltMC/quilt-loader/files/10528650/snapshot_beta62_slowest_2.zip). After the last edit I wiped the cache, ran the instance, it took 2min30sec + 5min20sec, then ran the instance with a snapshot capture right after. Sorry for a really messy comment, I hope I'm not making it harder, than it should be.

There's certainly some improvement, but not quite as it used to be and sometimes it takes even longer. Since the cache is now properly reused ([logs](https://gist.github.com/SplendidAlakey/ffd610065e9336cdd38752f5d16ebbc8) seem clean), I'm out of ideas as to why this happens. The instances, where it takes longer can go over 5min, ~~but I forgot to launch the JVVM during such an instance and now struggle to reproduce it.~~ I will, of course, re-test it again after the above crashes are fixed and will try to capture the slowest instance. If you see no obvious difference in the snapshots above, it might honestly be my SSD acting up.

The size of the resulting cache is 640MB, by the way. Not that it relates to anything, just letting you know, in case that's abnormal or something. All my mods combined are at 628MB.

**Comment by AlexIIL** [comment]
The Polymer & Frame API crash will probably be fixed with the same fix as https://github.com/QuiltMC/quilt-loader/issues/221, so I'll work on that next.

It turns out the charm crash is caused by not setting up our optimized classpath lookup correctly, so I'll fix that soon.

Nothing really jumps out to me as being quilt-loader itself being slow unfortunately :/

> If you see no obvious difference in the snapshots above, it might honestly be my SSD acting up.

It actually could be - some zip file reading takes 20 seconds to run in total, but only 10 seconds is actually spent in Java code. I don't know if that's just how the JVM reads files though. Either way you could always try checking your drive's health in settings? I don't want to blame slow loading times on just an SSD.

> The size of the resulting cache is 640MB, by the way. Not that it relates to anything, just letting you know, in case that's abnormal or something. All my mods combined are at 628MB.

Ouch. That's quite big, although sadly I don't think there's much I can do about it - however later betas changed the transform cache file, so you might be able to delete the older ones?
Old transform cache files are:
```
<minecraft>/.quilt/transform-cache.zip
<minecraft>/.quilt/transform-cache-client.zip
<minecraft>/.quilt/transform-cache-server.zip
```
The new transform cache file is `<minecraft>/.quilt/transform-cache-client/files.zip`, which should be the biggest one. It should probably be smaller than the total size of all your mods, but I can't guarantee that. (Plus ~22 MB for minecraft itself)

**Comment by SplendidAlakey** [comment]
> Nothing really jumps out to me as being quilt-loader itself being slow unfortunately :/

That's really weird... All the snapshots are practically identical instances, just some loading under acceptable times, and others not so much. And it seems to consistently happen after some time passes, using the latest betas. I don't even know what else could I test at this point.

> Either way you could always try checking your drive's health in settings? I don't want to blame slow loading times on just an SSD.

I did, actually. 0 issues were found and it's not all that worn down (sitting at 80%).

> Ouch. That's quite big, although sadly I don't think there's much I can do about it

Don't worry too much about it, just wanted to let you know, if nothing else, then for reference. I have enough space for it.

> however later betas changed the transform cache file, so you might be able to delete the older ones?

Oh, yeah I deleted them all completely when I was doing the tests. Because at first it seemed like with cache the loading was slower, than without. Unfortunately, it sounded too easy to be true and it ended up not being true, the loading times just get slower overtime for some reason. Like, once I update to the newest beta - usually runs great, things load fast, log filtering works etc. Changing anything, like updating a mod or a config, accelerates the slowdown, but I spent hours just mindlessly launching the game over and over again, and the times kept very slowly creeping up, occasionally dropping down a bit.

I will close this, when I can test the latest beta for crashes. The cache reusing issue itself is fixed, so it wasn't what caused my slowdowns, but still good it's fixed. If I can find out anything more about my slowdowns, I'll let you know.

**Comment by AlexIIL** [comment]
The only thing I can think of is that windows might not cache the whole transform cache in-memory after the first launch? I'm adding a cache preloader (enabled by default, use `-Dloader.transform_cache.disable_preload=true` to disable) to try and get that into windows's in-memory cache. I'm not sure if it will actually work but I don't know what else could be causing ever-decreasing loading times.

**Comment by AlexIIL** [comment]
Okay, that's out as beta 64 alongside the removal of separate classloaders.

**Comment by SplendidAlakey** [comment]
> The only thing I can think of is that windows might not cache the whole transform cache in-memory after the first launch?

Or my RAM is just too slow, it's fairly old and is only 2133MHz.

Unfortunately, I'm crashing even more on beta 64.

With [Kambrik](https://www.curseforge.com/minecraft/mc-mods/kambrik): 
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-kambrik_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-kambrik_latest-log

With Polymer: 
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-polymer_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-polymer_latest-log

With [Mushroom Additions](https://www.curseforge.com/minecraft/mc-mods/mushroom-additions): 
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-mushroom_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-mushroom_latest-log

With [Adorn](https://www.curseforge.com/minecraft/mc-mods/adorn): 
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-adorn_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-adorn_latest-log

With [Roughly Enough Trades](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-trades): 
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-trades_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-trades_latest-log

With [Immersive Aircraft](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft): 
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-aircraft_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-aircraft_latest-log

With [Immersive Paintings](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings): 
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-paintings_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-paintings_latest-log

With [Capes](https://www.curseforge.com/minecraft/mc-mods/capes): 
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-capes_crash-log
https://gist.github.com/SplendidAlakey/91a82e6df8c45eba1dfb6a30327f547f#file-capes_latest-log

**Comment by AlexIIL** [comment]
Sorry, I didn't test my releases properly. Those two (similar) bugs should now be fixed in beta 65.

**Comment by SplendidAlakey** [comment]
All the crashes are fixed, thanks!

I'm closing this, because the cache is now being reused properly, but, sadly, my loading times remained exactly the same, so not reusing the cache was not the issue. I'm now seeing these lines, which pretty much indicate 0 issues with caching:
```
transform-cache took 5548ms 
zip sub copy took 281ms 
tmp jar copy took 79ms
 mod adding took 18ms
```
I have my suspicions, due to Log Begone failing to work, so I'll just be going through my mods, trying to see if something breaks logging, which in turn slows things down or something.

Edit: if anyone finds this thread, while trying to bring MC loading times down - my issue was caused by windows balanced energy mode, switching to high performance completely solved it.
