### ISSUE TITLE
Filesystem errors  on Windows caused by wrong implementation of QuiltBasePath

### ISSUE THREAD

**Issue by CheaterCodes** [QuiltMC/quilt-loader#227]
As mentioned in #222, there seems to be an issue on Windows when locating chasm transformers. Upon closer investigation, this appreas to be a more general Problem with the optimised compressed transform cache, since the problem is fixed when using `loader.transform_cache.disable_optimised_compression`.

After some investigation, I noticed the following:
- When using the optimised compressed transform cache, Quilt uses th QuiltMemoryFileSystem.
- In this case, the root will be a QuiltMemoryPath.
- During remapping, quilt-laoder walks the mod root path.
- On Windows only, when walking a directory root path for a mod, the path will be of type `WindowsPath`
- Windows path uses backwards slashes `\`
- The file path is relativized to the mod root and then appended to the transform cache root path.
- the windows path is converted using `toString`, which is likely a hack to get around a class cast issue
- The entire relative path is not considered the file *name* since it's separated by backslashes

Proposed solution:
Fix `QuiltBasePath.resolve(Path other)` to be path type agnostic (instead of doing unchecked class casting). In particular, `Path` is iterable, so this should be easy enough Additionally, fix QFS and co to be completely separator agnostic.

**Comment by CheaterCodes** [comment]
After looking at QFS and co, I feel like there is a lot of improvement in terms of sound file handling here. Would it be ok if I did a thorough clean-up of those classes in a PR?

**Comment by AlexIIL** [comment]
Unfortunately `Path.resolve(Path)` is defined to not accept paths from other file systems :/
