### ISSUE TITLE
Crashes when replaced with Quilt Loader 0.18.1-beta.64

### ISSUE THREAD

**Issue by RegulusSource** [QuiltMC/quilt-loader#228]
[crash-2023-01-30_01.14.27-client.txt](https://github.com/QuiltMC/quilt-loader/files/10530394/crash-2023-01-30_01.14.27-client.txt)
[crash-2023-01-30_01.12.18-client.txt](https://github.com/QuiltMC/quilt-loader/files/10530395/crash-2023-01-30_01.12.18-client.txt)

**Comment by coderbot16** [comment]
This is also causing crashes with Iris:

[2023-01-29-3.log](https://github.com/QuiltMC/quilt-loader/files/10531131/2023-01-29-3.log)

**Comment by AlexIIL** [comment]
Thanks for the reports! This should be fixed in beta 65.
