### ISSUE TITLE
Semantic versions from Fabric mods return false for isSemantic()

### ISSUE THREAD

**Issue by ghost** [QuiltMC/quilt-loader#230]
Have tested 0.17.10 and 0.17.6, cannot test 0.18.1 betas due to another issue.
e.g. 
```java
// carrier is a fabric mod
QuiltLoader.getModContainer("carrier").metadata().version().isSemantic() // returns false
```

**Comment by TheGlitch76** [comment]
This should work in 0.18.1. I added a workaround in 0.17.11 which should resolve your issue.
