### ISSUE TITLE
Some unicode characters missing since 0.18.1-beta.42 (Minecraft versions >1.17.1-rc2, <22w11a)

### ISSUE THREAD

**Issue by macbrayne** [QuiltMC/quilt-loader#233]
This issue also happens without QSL or JourneyMap installed.

Expected behaviour:
![image](https://user-images.githubusercontent.com/27809595/216640984-2432b6cb-3277-4541-8af7-6d078bc8571d.png)
Behaviour since beta.42:
![image](https://user-images.githubusercontent.com/27809595/216641022-57ffd0e4-5011-434d-8b43-f62d04da3c40.png)

Logs don't give seem to give any hint of what's happening 
Logs across versions: https://gist.github.com/macbrayne/76b88173c36622dc5b9602a3184ec707
Reproduced on MultiMC and PrismLauncher, not sure if that matters
See: https://discord.com/channels/817576132726620200/1071067936304934952

**Comment by macbrayne** [comment]
The case above only happens with Force-Unicode enabled.

Further examples:
![image](https://user-images.githubusercontent.com/27809595/216644816-849fab66-449e-496e-9bc4-6d9ea341dbfa.png)
(renders fine without force-unicode)

Some languages on the other hand still render with the normal Minecraft font even with force-unicode enabled...
![image](https://user-images.githubusercontent.com/27809595/216645014-59dbab56-c7ce-4ecb-b7d4-c2801d89c02f.png)
...but don't render with force-unicode disabled either (might be a separate issue). 
![image](https://user-images.githubusercontent.com/27809595/216645083-61f0ba9c-0bac-46d0-86a4-2587ae9d9eb0.png)

**Comment by macbrayne** [comment]
Minecraft versions 22w11a (1.19) and up are not affected
Minecraft versions 1.17.1 - 1.18.2 are affected
Minecraft versions 1.17.1-rc2 and under (only tested down to 1.16.5) are not affected
(tested by looking for boxes in the language selection menu with force-unicode on and off)

**Comment by AlexIIL** [comment]
Okay, this should be fixed in beta 68 - can you retry?

**Comment by macbrayne** [comment]
Fixed! ✔️ 
![image](https://user-images.githubusercontent.com/27809595/216780029-b9ff0ae0-e027-45da-b12a-acb9ac103de8.png)

**Comment by macbrayne** [comment]
Also works:
![image](https://user-images.githubusercontent.com/27809595/216780061-3713884d-d07f-4d29-8207-b6d9752c6476.png)

**Comment by AlexIIL** [comment]
Thanks for testing :)
