### ISSUE TITLE
Crash on dedicated servers using Java 8 with 0.18.1 Beta 61-66

### ISSUE THREAD

**Issue by JulianVennen** [QuiltMC/quilt-loader#234]
All Quilt Loader 0.18.1 Betas starting with version 61 crash when used on a server with Java 8.
Log: https://mclo.gs/q643RQb
This log uses 1.16.5 as an example, but this also affects all other Minecraft versions that support Java 8.
1.16.5 works if I use Java 11

**Comment by AlexIIL** [comment]
Okay, this should be fixed in beta 67 and later, and I've added a java 8 server to my personal test suite so hopefully future updates won't randomly break this again

**Comment by JulianVennen** [comment]
Thank you, I can confirm that it is fixed.
