### ISSUE TITLE
No API way to get non-SemVer minecraft version without classloading minecraft classes

### ISSUE THREAD

**Issue by lukebemish** [QuiltMC/quilt-loader#235]
Currently, the only ways I can find to get the normal, non-semver-ified minecraft version (which I need to query piston-meta) are either internal (`QuiltLoaderImpl`, get the game provider, get the raw version) or involve classloading a minecraft class (`SharedConstants`), which though it works for now will not in the long term, especially since much of this logic will be moved to a loader plugin once those are available. Is there any chance we could get an API method for getting the raw, non-semver-ified game version?

**Comment by AlexIIL** [comment]
Both methods can just be exposed in `QuiltLoader` directly, since I assume most games will have a concept of versions.

**Comment by lukebemish** [comment]
I believe this can be closed, since an API was added in a recent update
