### ISSUE TITLE
Can't hard-depend on chasm before it's had a release

### ISSUE THREAD

**Issue by AlexIIL** [QuiltMC/quilt-loader#236]
This likely means invoking chasm via reflection and method handles, at least before it gets a release. (And also PRing a reflected API  into chasm)

Unless you have any other ideas @CheaterCodes ?

**Comment by CheaterCodes** [comment]
I mean, yes. We could make a Chasm "release". I don't mind publishing 0.1.0, or maybe beta versions. We just never had a reason to do that.

**Comment by TheGlitch76** [comment]
Fixed in https://github.com/QuiltMC/quilt-loader/commit/45e76713c415f27f22293e03d7bc67dbddb9c26f
