### ISSUE TITLE
[Suggestion] Add a slider in the crash screen

### ISSUE THREAD

**Issue by stantios** [QuiltMC/quilt-loader#240]
Description: On 0.18.x betas and only for mods that have long names, some of the text goes off the window which you can't see. It would be useful if there slider to scroll to the right of the screen so you could see the text without having to make the window bigger.

Screenshots: 
![image](https://user-images.githubusercontent.com/98621617/219354865-6a46afaa-4c91-4f1c-9cd0-4e97bdff3bb6.png)

**Comment by AlexIIL** [comment]
I don't think it used to have a horizontal scroll bar because that caused *some problems*, but as I can't reproduce them now I'll add it back.

(Its possible that the problems only occurred when we were adding the window and tweaking its layout rather than more recently).
