### ISSUE TITLE
Crash at launch - Internal Error ! 

### ISSUE THREAD

**Issue by petitmoutard** [QuiltMC/quilt-loader#249]
[crashreport.txt](https://github.com/QuiltMC/quilt-loader/files/10831803/crashreport.txt)

MC : 1.19.3
QL : 0.18.2

![image](https://user-images.githubusercontent.com/86343998/221370074-633a5d9b-f798-4fb6-8f8c-adbf180ce86d.png)

**Comment by AlexIIL** [comment]
This should be fixed in quilt loader beta `0.18.3-pre.1`, can you try updating to that version?

**Comment by petitmoutard** [comment]
[crash-2023-02-26_00.15.19-client.txt](https://github.com/QuiltMC/quilt-loader/files/10832492/crash-2023-02-26_00.15.19-client.txt)

I tried again and it crashes again

**Comment by AlexIIL** [comment]
It looks like `Vinery` hasn't been updated to 1.19.3 yet, and you've got an outdated version of `Magic Combat Wands` - try downloading 1.0.4 instead? (https://www.curseforge.com/minecraft/mc-mods/magic-combat-wands/files/4401017).

**Comment by petitmoutard** [comment]
Yes it works, but there is a bug I think :

I launched my game in the default directory. But, when I launched it, it took mods that are in another directory, in my mods file. It has never done that before... 

Because Vinery & Magic Combat Wands are in a forge directory in 1.19.2. 

`<mods>/modpack/mods`
-----↓---------------↓----------
 Default.....|....Forge 
Directory...|..Directory

**Comment by AlexIIL** [comment]
That's a new feature in loader 0.18.1 - loading from sub-folders. This is mostly useful for organizing a lot of mods, but it can be disabled by changing the option `load_sub_folders` to `false` in `config/quilt-loader.txt`.

**Comment by petitmoutard** [comment]
Ok thanks !
