### ISSUE TITLE
Quilted Fabric API failure in 1.19.3

### ISSUE THREAD

**Issue by Potato22** [QuiltMC/quilt-loader#253]
![image](https://user-images.githubusercontent.com/39096741/221547531-af646649-3e56-4ab7-94d7-bdd9d762412b.png)
the log is quite long, uploaded here: https://paste.ee/p/lSNPe

The log feels a little unspecific, it said to report it to Quilt since this is the error coming from Quilted Fabric API and so I did. Let me know if there's a solution or workarounds.

**Comment by TheGlitch76** [comment]
This error is unrelated to Quilt Loader; it looks like you are using Illuminations (a mod which is for 1.19.2) on 1.19.3, and it is not compatible.
In the future, You can get help for support questions like this on either our [forum](https://forum.quiltmc.org/c/support/9) or [Discord server](discord.quiltmc.org).
