### ISSUE TITLE
Standard cache directory

### ISSUE THREAD

**Issue by LostLuma** [QuiltMC/quilt-loader#254]
Loader could provide a standardized cache directory for temporary-ish files mods generate at runtime, similar to the config directory.

I'd like to see this as mods currently put these files all over the place such as directly inside the game directory, folders in the game directory, or even mixed in with config files. This can cause visual clutter when opening the game directory or cause these files to be wrongly included when being shared (privately or in a modpack).

Some existing examples of such folders are loaders own `.quilt` folder and the `mod_data` folder used by some mods.

**Comment by AlexIIL** [comment]
Perhaps `.cache`? That would match the name in linux, and then we could move the `.quilt` folder to use `.cache/quilt_loader` instead.

**Comment by lukebemish** [comment]
As one of the people currently using `mod_data`, I like `.cache`
