### ISSUE TITLE
Add a system property for disabling the Swing-based error screens

### ISSUE THREAD

**Issue by zeichenreihe** [QuiltMC/quilt-loader#259]
Quilt-loader should check another system property (via `Boolean.getBoolean()`, next to swings `java.awt.headless`) to decide if it should open it's error screen. This would allow passing something like `-Dquilt.loader.noErrorScreen=true` to java, to not get an error screen like the one tells you that "a mod crashed on startup" or "mod dependency missing".

I don't like getting a popup screen when you're runing quilt-loader in an development environment where you already have a log window or in prismlauncher, where in case mc crashes you also get a log window.
In case it doesn't open an error screen, it should just rethrow the exception.

I cannot use the `java.awt.headless` property, as that
- could potentially mess up things in the launched application (mc)
- prevents mods from using any of the swift components, like `JFileChooser` (yes mods shouldn't use that, but who wants to implement a FileChooser that runs inside mc when you just need a quick and dirty way of selecting files to save/load)

my message in the quilt community discord about this: <https://discord.com/channels/817576132726620200/833939559636271105/1084512643139784714>

**Comment by TheGlitch76** [comment]
Implemented in https://github.com/QuiltMC/quilt-loader/commit/333de28e694737dc31a4cee08acc92fc0fc98e54
