### ISSUE TITLE
Better entrypoints

### ISSUE THREAD

**Issue by LambdAurora** [QuiltMC/quilt-loader#26]
This issue might be closed once entrypoints are not in loader anymore.

Entrypoints should have a `ModContainer` parameter passed to them, I don't know why it wasn't from the start but it can be pretty annoying in the case a mod needs to get its `ModContainer` as it has to get it with a call using its own mod id which returns an `Optional`.

This mostly have a use-case for resource loader and the built-in resource packs, could be used for other things too.
It's also a way to get the root `Path` of the mod.

**Comment by i509VCB** [comment]
I have an idea how I'd approach this, can't detail it now.

**Comment by i509VCB** [comment]
Okay I need to not leave everyone on a cliffhanger, so here is my idea:

We introduce a `GameEntrypoint` interface into loader. This is part of core loader and is itself just an empty interface. This interface itself should not be implemented by mods, but instead by the public api for a game's provider.

Why introduce this interface, it allows a minimum interface type bound for the game provider to use to get the interface and game providers would extend this interface. And allows us to introduce new extended interfaces without breaking existing mods.

Example:
```java
@NonExtendable // Nonextendable to mods only
public interface GameEntrypoint {}

// In the Minecraft API for loader

public interface MinecraftMainEntrypoint extends GameEntrypoint {
    void init(ModContainer mod);
}
```

Say in a future version we need to add a new parameter to this entrypoint, then we would introduce a new `MinecraftMainEntrypointV2`. This new interface would extend `GameEntrypoint`. The Minecraft game provider would then do an instanceof check and call the specific variant of the entrypoint implemented. To the game provider, it would load the entrypoint under a `GameEntrypoint` type but cast as necessary.

**Comment by AlexIIL** [comment]
@i509VCB That sounds interesting, but I don't that that's directly relevant to this issue - since we can do that separately from implementing this in #29?

(Since, *as far as I can tell*, that doesn't affect how mods use entrypoints - only how we implement the invocation of entrypoints in loader)

**Comment by AlexIIL** [comment]
Entrypoints are now in QSL (https://github.com/QuiltMC/quilt-standard-libraries/commit/4a21e68e8923b3e3dc06ff70c08a5b3ac9dd8ae2), and this has been implemented in quilt-loader for `PreLaunchEntrypoint`.
