### ISSUE TITLE
help TwT

### ISSUE THREAD

**Issue by Freinzz** [QuiltMC/quilt-loader#269]
RU
Прошу помощи в решении проблемы. 
EN
I ask for help in solving the problem.
1.
[crash.txt](https://github.com/QuiltMC/quilt-loader/files/11105753/crash.txt)
2.
[crash-2023-03-30_24.44.52.9065-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/11105752/crash-2023-03-30_24.44.52.9065-quilt_loader.txt)

**Comment by TheGlitch76** [comment]
The error message means that "kennytv's epic force close loading screen mod (forcecloseloadingscreen)" says it does not work with "FastLoad". You have to remove either "FastLoad" or the "force close loading screen" mod. You can not use these mods together. If this is an issue, consider talking to the author of "forcecloseloadingscreen".

In the future, please ask for help on our [forum](https://forum.quiltmc.org/c/support/9) or [Discord server](https://discord.quiltmc.org). You will get faster and better help.
