### ISSUE TITLE
`provides` do not follow expected behavior according to RFC 2 (Essential + QKL fix)

### ISSUE THREAD

**Issue by SilverAndro** [QuiltMC/quilt-loader#279]
The [versions field](https://github.com/QuiltMC/rfcs/blob/main/specification/0002-quilt.mod.json.md#the-version-field-1) for a QMJ file says that it should unless omitted, use the provided version. Instead [this line](https://github.com/QuiltMC/quilt-loader/blob/4cd133879cb0c4530da982128aef13f1f42023b1/src/main/java/org/quiltmc/loader/impl/QuiltLoaderImpl.java#L1030) causes quilt to re-add the mod that is providing under the provided ID instead of the dummy provided metadata.

This causes issues with Essential + QKL, as although QKL [provides a specific FLK version](https://github.com/QuiltMC/quilt-kotlin-libraries/blob/f0c7819b3314aad01e2b8a06190b7824f15ad07e/core/src/main/resources/quilt.mod.json#L31), Essential reads the version of QKL when trying to get the version from the mod container as part of its auto update code, spitting out `An older version (1.0.2) of mod fabric-language-kotlin (1.8.2+kotlin.1.7.10) is already loaded, updating..`

FTR, fabric loader has this behavior as well, although given their spec is out of date, i cant find if that is intentional or not

**Comment by AlexIIL** [comment]
Okay, this should be fixed in beta 11, can you retry?

**Comment by SilverAndro** [comment]
yep works great! thanks much <3
