### ISSUE TITLE
QuiltBaseFileSystem doesn't support 'glob' path matching.

### ISSUE THREAD

**Issue by AlexIIL** [QuiltMC/quilt-loader#285]
https://github.com/QuiltMC/quilt-loader/blob/2a45297b4e95966d11c90e2d1e2ece1f6794daff/src/main/java/org/quiltmc/loader/impl/filesystem/QuiltBaseFileSystem.java#L211

**Comment by TheGlitch76** [comment]
https://github.com/QuiltMC/quilt-loader/commit/54e48387ba39f064b52bc2ebfc87361d93d97113
