### ISSUE TITLE
Via Fabric Plus-2.1.0 seems to break on QuiltLoader on windows 10.

### ISSUE THREAD

**Issue by AxolotlBro** [QuiltMC/quilt-loader#295]
[ViaFabricPlus](https://modrinth.com/mod/viafabricplus) seems to break on Quilt Loader.

Steps to reproduce:

1. Make sure you are on a windows 10 machine.
2. Install this mod along with Fabric API on a Quilt instance.
3. Start the game.
4. Quilt loader break

![image](https://user-images.githubusercontent.com/131779254/234287638-55522ac5-6876-4a6b-9843-41ad3d32e6d4.png)
![image](https://user-images.githubusercontent.com/131779254/234287652-7bbb54ea-d8ea-4144-99ef-b28e71199a19.png)

Logs:  [crash-2023-04-25_16.14.53.3482-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/11322864/crash-2023-04-25_16.14.53.3482-quilt_loader.txt)

**Comment by AlexIIL** [comment]
Sadly Quilt-Loader does a terrible job of describing this at the moment, but it's because your version of `viafabricplus` has declared itself to be incompatible with Krypton (`<mods>\krypton-0.2.1.jar`)

**Comment by Gaming32** [comment]
I think it might be better to show what's in the log than "Quilt Loader has crashed.". It's not better than proper error messages, but it's better than nothing.

**Comment by TheGlitch76** [comment]
I've opened #309 to consolidate these issues. If you're still having trouble, there's a link for finding better support there.
