### ISSUE TITLE
Forked communication failure; check the log for details!

### ISSUE THREAD

**Issue by heipiao233** [QuiltMC/quilt-loader#299]
This is a bug caused by 05fed1d, in this commit, @TheGlitch76 "write classpath to file". This causes the problem: If there is spaces in the classpath, JVM thinks there is two or more arguments, so the second part passed to JVM as main class, but it is not exist, so the server process stops. Then all GUI can't show, and even causes crash.

IDEA generates the argument file correctly (idea_arg_filexxxxxxxx):
![Spaces are wrapped in quotation marks](https://user-images.githubusercontent.com/81846300/235351153-330562f9-36ea-4568-89d6-c0bce2d14c9f.png)
But Quilt doesn't (comms.cp):
![Not wrapped](https://user-images.githubusercontent.com/81846300/235351173-7b57f7e9-76c2-4c37-a9e1-1ded4fbe9ff5.png)

**Comment by AlexIIL** [comment]
This should be fixed in 0.19.0, can you retry?

**Comment by eristhea** [comment]
@heipiao233 closing this issue as it's gone stale, feel free to reopen if you can still reproduce the issue on latest!
