### ISSUE TITLE
oh no crash

### ISSUE THREAD

**Issue by mushMario** [QuiltMC/quilt-loader#301]
---- Quilt Loader: Failed to load ----
Date/Time: 2023/05/06 18:04:47.2139

-- Error 1 --

Unhandled solver error involving the following rules:
Rule 1:
Mandatory mod quiltgoslightlyfasterlol (quiltgoslightlyfasterlol) v0.0.3
Rule 2:
Mandatory mod AutoModpack (automodpack) v3.3.0
Rule 3:
Breakage for {org.quiltmc.loader.impl.plugin.quilt.QuiltModOption 'automodpack' from <mods>/automodpack-3.3.0-1.18.2.jar} on quiltgoslightlyfasterlol versions [*] (1 breaking options, 0 okay options)
	x {org.quiltmc.loader.impl.plugin.quilt.QuiltModOption 'quiltgoslightlyfasterlol' from <mods>/quiltgoslightlyfasterlol-0.0.3.jar} {org.quiltmc.loader.impl.plugin.quilt.QuiltModOption 'quiltgoslightlyfasterlol' from <mods>/quiltgoslightlyfasterlol-0.0.3.jar}

-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)

-- Mod Table --

| Mod                                   | ID                                   | Version            | Plugin                 | File(s)                                                                                                | Sub-Files                                                                |
|---------------------------------------|--------------------------------------|--------------------|------------------------|--------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|
| AutoModpack                           | automodpack                          | 3.3.0              | quilt_loader           | <mods>\automodpack-3.3.0-1.18.2.jar                                                                    |                                                                          |
| Cloth Config v6                       | cloth-config                         | 6.3.81             | quilted_fabric_loader  | <mods>\cloth-config-6.3.81-fabric.jar                                                                  |                                                                          |
| Cloth Config v6                       | cloth-config                         | 6.3.81             | quilted_fabric_loader  | <mods>\cloth-config-6.3.81-fabric.jar                                                                  |                                                                          |
| Cull Less Leaves                      | cull-less-leaves                     | 1.0.1              | quilted_fabric_loader  | <mods>\[更好的树叶渲染优化] CullLessLeaves-1.0.1.jar                                                            |                                                                          |
| DashLoader                            | dashloader                           | 4.1.3+1.18         | quilted_fabric_loader  | <mods>\[疾速加载] dashloader-4.1.3+1.18.jar                                                                |                                                                          |
| Disable Custom Worlds Advice          | disable_custom_worlds_advice         | 2.0                | quilted_fabric_loader  | <mods>\DisableCustomWorldsAdvice-2.0.jar                                                               |                                                                          |
| Fabric API Base                       | fabric-api-base                      | 0.4.3+d7c144a8d2   | quilted_fabric_loader  | <mods>\[钠] sodium-fabric-mc1.18.2-0.4.1+build.15.jar                                                   | /META-INF/jars/fabric-api-base-0.4.3+d7c144a8d2.jar                      |
| Fabric Key Binding API (v1)           | fabric-key-binding-api-v1            | 1.0.12+54e5b2ec60  | quilted_fabric_loader  | <mods>\iris-mc1.18.2-1.6.2.jar                                                                         | /META-INF/jars/fabric-key-binding-api-v1-1.0.12+54e5b2ec60.jar           |
| Fabric Rendering Data Attachment (v1) | fabric-rendering-data-attachment-v1  | 0.3.6+d7c144a8d2   | quilted_fabric_loader  | <mods>\[钠] sodium-fabric-mc1.18.2-0.4.1+build.15.jar                                                   | /META-INF/jars/fabric-rendering-data-attachment-v1-0.3.6+d7c144a8d2.jar  |
| Fabric Rendering Fluids (v1)          | fabric-rendering-fluids-v1           | 2.0.1+54e5b2ecd2   | quilted_fabric_loader  | <mods>\[钠] sodium-fabric-mc1.18.2-0.4.1+build.15.jar                                                   | /META-INF/jars/fabric-rendering-fluids-v1-2.0.1+54e5b2ecd2.jar           |
| Fabric Resource Loader (v0)           | fabric-resource-loader-v0            | 0.4.16+55dca1a4d2  | quilted_fabric_loader  | <mods>\[钠] sodium-fabric-mc1.18.2-0.4.1+build.15.jar                                                   | /META-INF/jars/fabric-resource-loader-v0-0.4.16+55dca1a4d2.jar           |
| FastQuit                              | fastquit                             | 1.2.2+1.18.2       | quilted_fabric_loader  | <mods>\fastquit-1.2.2+1.18.2.jar                                                                       |                                                                          |
| Hyphen                                | dev_quantumfusion_hyphen             | 0.2.2              | quilted_fabric_loader  | <mods>\[疾速加载] dashloader-4.1.3+1.18.jar                                                                | /META-INF/jars/Hyphen-0.2.2.jar                                          |
| Iris                                  | iris                                 | 1.6.2              | quilted_fabric_loader  | <mods>\iris-mc1.18.2-1.6.2.jar                                                                         |                                                                          |
| Java HotSpot(TM) 64-Bit Server VM     | java                                 | 17                 | quilt_loader           | C:\Program Files\Java\jdk-17                                                                           |                                                                          |
| Memory Leak Fix                       | memoryleakfix                        | 1.0.0              | quilted_fabric_loader  | <mods>\memoryleakfix-fabric-1.17+-1.0.0.jar                                                            |                                                                          |
| Minecraft                             | minecraft                            | 1.18.2             | quilt_loader           | <game>\.quilt\remappedJars\minecraft-1.18.2-0.18.10\client-intermediary.jar                            |                                                                          |
| MixinExtras                           | com_github_llamalad7_mixinextras     | 0.2.0-beta.6       | quilted_fabric_loader  | <mods>\memoryleakfix-fabric-1.17+-1.0.0.jar                                                            | /META-INF/jars/mixinextras-fabric-0.2.0-beta.6.jar                       |
| MixinExtras                           | com_github_llamalad7_mixinextras     | 0.1.1              | quilted_fabric_loader  | <mods>\fastquit-1.2.2+1.18.2.jar                                                                       | /META-INF/jars/MixinExtras-0.1.1.jar                                     |
| Quilt Loader                          | quilt_loader                         | 0.18.10            | quilt_loader           | <user>\AppData\Roaming\.minecraft\libraries\org\quiltmc\quilt-loader\0.18.10\quilt-loader-0.18.10.jar  |                                                                          |
| Quilt Loader                          | quilt_loader                         | 0.18.10            | quilt_loader           | <user>\AppData\Roaming\.minecraft\libraries\org\quiltmc\quilt-loader\0.18.10\quilt-loader-0.18.10.jar  |                                                                          |
| Smooth Menu                           | smoothmenu                           | 1.0.0              | quilted_fabric_loader  | <mods>\smoothmenu-1.0.0.jar                                                                            |                                                                          |
| Sodium                                | sodium                               | 0.4.1+build.15     | quilted_fabric_loader  | <mods>\[钠] sodium-fabric-mc1.18.2-0.4.1+build.15.jar                                                   |                                                                          |
| Taski                                 | dev_quantumfusion_taski              | 1.1.0              | quilted_fabric_loader  | <mods>\[疾速加载] dashloader-4.1.3+1.18.jar                                                                | /META-INF/jars/Taski-1.1.0.jar                                           |
| antlr4-runtime                        | org_antlr_antlr4-runtime             | 4.11.1             | quilted_fabric_loader  | <mods>\iris-mc1.18.2-1.6.2.jar                                                                         | /META-INF/jars/antlr4-runtime-4.11.1.jar                                 |
| cloth-basic-math                      | cloth-basic-math                     | 0.6.1              | quilted_fabric_loader  | <mods>\cloth-config-6.3.81-fabric.jar                                                                  | /META-INF/jars/basic-math-0.6.1.jar                                      |
| glsl-transformer                      | io_github_douira_glsl-transformer    | 2.0.0-pre13        | quilted_fabric_loader  | <mods>\iris-mc1.18.2-1.6.2.jar                                                                         | /META-INF/jars/glsl-transformer-2.0.0-pre13.jar                          |
| jcpp                                  | org_anarres_jcpp                     | 1.4.14             | quilted_fabric_loader  | <mods>\iris-mc1.18.2-1.6.2.jar                                                                         | /META-INF/jars/jcpp-1.4.14.jar                                           |
| joml                                  | org_joml_joml                        | 1.10.2             | quilted_fabric_loader  | <mods>\[钠] sodium-fabric-mc1.18.2-0.4.1+build.15.jar                                                   | /META-INF/jars/joml-1.10.2.jar                                           |
| mixinextras                           | com_github_llamalad7_mixinextras     | 0.0.9              | quilted_fabric_loader  | <mods>\[更好的树叶渲染优化] CullLessLeaves-1.0.1.jar                                                            | /META-INF/jars/mixinextras-0.0.9.jar                                     |
| quiltgoslightlyfasterlol              | quiltgoslightlyfasterlol             | 0.0.3              | quilt_loader           | <mods>\quiltgoslightlyfasterlol-0.0.3.jar                                                              |                                                                          |
| zstd-jni                              | com_github_luben_zstd-jni            | 1.5.2-2            | quilted_fabric_loader  | <mods>\[疾速加载] dashloader-4.1.3+1.18.jar                                                                | /META-INF/jars/zstd-jni-1.5.2-2.jar                                      |
|---------------------------------------|--------------------------------------|--------------------|------------------------|--------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|

-- Mod Details --

C:\Program Files\Java\jdk-17:
####################################################
#  Loaded by  'quilt_loader'                       #
#  Name     = 'Java HotSpot(TM) 64-Bit Server VM'  #
#  ID       = 'java'                               #
#  Version  = '17'                                 #
#  LoadType = IF_REQUIRED                          #
####################################################

<user>\AppData\Roaming\.minecraft\libraries\org\quiltmc\quilt-loader\0.18.10\quilt-loader-0.18.10.jar:
#######################################
#  Loaded by  'quilt_loader'          #
#  Name     = 'Quilt Loader'          #
#  ID       = 'quilt_loader'          #
#  Version  = '0.18.10'               #
#  LoadType = IF_REQUIRED             #
#  Provides   'fabricloader' 0.14.19  #
#######################################

<game>\.quilt\remappedJars\minecraft-1.18.2-0.18.10\client-intermediary.jar:
###############################
#  Loaded by  'quilt_loader'  #
#  Name     = 'Minecraft'     #
#  ID       = 'minecraft'     #
#  Version  = '1.18.2'        #
#  LoadType = IF_REQUIRED     #
#  Depends on 'java' [17, ∞)  #
###############################

<mods>\automodpack-3.3.0-1.18.2.jar:
###################################################
#  Loaded by  'quilt_loader'                      #
#  Name     = 'AutoModpack'                       #
#  ID       = 'automodpack'                       #
#  Version  = '3.3.0'                             #
#  LoadType = IF_REQUIRED                         #
#  Depends on 'quilt_loader' [0.17.0, ∞)          #
#  Depends on 'minecraft' [1.18, 2)               #
#  Breaks  on 'quiltgoslightlyfasterlol' (-∞, ∞)  #
###################################################

<mods>\cloth-config-6.3.81-fabric.jar:
##############################################
#  Loaded by  'quilted_fabric_loader'        #
#  Name     = 'Cloth Config v6'              #
#  ID       = 'cloth-config'                 #
#  Version  = '6.3.81'                       #
#  LoadType = IF_POSSIBLE                    #
#  Provides   'cloth-config2' 6.3.81         #
#  Depends on 'fabricloader' [0.9.0, ∞)      #
#                                            #
#  Contained Jars (1):                       #
#                                            #
#  /META-INF/jars/basic-math-0.6.1.jar:      #
#  +--------------------------------------+  #
#  |  Loaded by  'quilted_fabric_loader'  |  #
#  |  Name     = 'cloth-basic-math'       |  #
#  |  ID       = 'cloth-basic-math'       |  #
#  |  Version  = '0.6.1'                  |  #
#  |  LoadType = IF_POSSIBLE              |  #
#  +--------------------------------------+  #
#                                            #
##############################################

<mods>\DisableCustomWorldsAdvice-2.0.jar:
###############################################
#  Loaded by  'quilted_fabric_loader'         #
#  Name     = 'Disable Custom Worlds Advice'  #
#  ID       = 'disable_custom_worlds_advice'  #
#  Version  = '2.0'                           #
#  LoadType = IF_POSSIBLE                     #
#  Depends on 'fabricloader' (-∞, ∞)          #
#  Depends on 'minecraft' [1.18.2, 1.19)      #
###############################################

<mods>\fastquit-1.2.2+1.18.2.jar:
#########################################################
#  Loaded by  'quilted_fabric_loader'                   #
#  Name     = 'FastQuit'                                #
#  ID       = 'fastquit'                                #
#  Version  = '1.2.2+1.18.2'                            #
#  LoadType = IF_POSSIBLE                               #
#  Depends on 'fabricloader' [0.14.9, ∞)                #
#  Depends on 'minecraft' [1.18.2, 1.18.2]              #
#  Depends on 'fabric-resource-loader-v0' (-∞, ∞)       #
#  Depends on 'java' [17, ∞)                            #
#                                                       #
#  Contained Jars (1):                                  #
#                                                       #
#  /META-INF/jars/MixinExtras-0.1.1.jar:                #
#  +-------------------------------------------------+  #
#  |  Loaded by  'quilted_fabric_loader'             |  #
#  |  Name     = 'MixinExtras'                       |  #
#  |  ID       = 'com_github_llamalad7_mixinextras'  |  #
#  |  Version  = '0.1.1'                             |  #
#  |  LoadType = IF_POSSIBLE                         |  #
#  +-------------------------------------------------+  #
#                                                       #
#########################################################

<mods>\iris-mc1.18.2-1.6.2.jar:
#####################################################################
#  Loaded by  'quilted_fabric_loader'                               #
#  Name     = 'Iris'                                                #
#  ID       = 'iris'                                                #
#  Version  = '1.6.2'                                               #
#  LoadType = IF_POSSIBLE                                           #
#  Depends on 'fabricloader' [0.12.3, ∞)                            #
#  Depends on 'minecraft' [1.18, 1.19)                              #
#  Breaks  on 'iris-explorer' (-∞, ∞)                               #
#  Breaks  on 'originsenhanced' (-∞, 1.3.2]                         #
#  Breaks  on 'colormatic' (-∞, 3.0.0]                              #
#  Breaks  on 'bedrockwaters' (-∞, 1.6.0]                           #
#  Breaks  on 'batchedentityrendering' (-∞, ∞)                      #
#  Breaks  on 'canvas' (-∞, ∞)                                      #
#  Breaks  on 'optifabric' (-∞, ∞)                                  #
#  Breaks  on 'worldeditcui' (-∞, 1.18.1)                           #
#  Breaks  on 'immersive_portals' (-∞, 1.4.2]                       #
#                                                                   #
#  Contained Jars (4):                                              #
#                                                                   #
#  /META-INF/jars/antlr4-runtime-4.11.1.jar:                        #
#  +-----------------------------------------+                      #
#  |  Loaded by  'quilted_fabric_loader'     |                      #
#  |  Name     = 'antlr4-runtime'            |                      #
#  |  ID       = 'org_antlr_antlr4-runtime'  |                      #
#  |  Version  = '4.11.1'                    |                      #
#  |  LoadType = IF_POSSIBLE                 |                      #
#  +-----------------------------------------+                      #
#                                                                   #
#  /META-INF/jars/fabric-key-binding-api-v1-1.0.12+54e5b2ec60.jar:  #
#  +--------------------------------------------+                   #
#  |  Loaded by  'quilted_fabric_loader'        |                   #
#  |  Name     = 'Fabric Key Binding API (v1)'  |                   #
#  |  ID       = 'fabric-key-binding-api-v1'    |                   #
#  |  Version  = '1.0.12+54e5b2ec60'            |                   #
#  |  LoadType = IF_POSSIBLE                    |                   #
#  |  Depends on 'fabricloader' [0.4.0, ∞)      |                   #
#  +--------------------------------------------+                   #
#                                                                   #
#  /META-INF/jars/glsl-transformer-2.0.0-pre13.jar:                 #
#  +--------------------------------------------------+             #
#  |  Loaded by  'quilted_fabric_loader'              |             #
#  |  Name     = 'glsl-transformer'                   |             #
#  |  ID       = 'io_github_douira_glsl-transformer'  |             #
#  |  Version  = '2.0.0-pre13'                        |             #
#  |  LoadType = IF_POSSIBLE                          |             #
#  +--------------------------------------------------+             #
#                                                                   #
#  /META-INF/jars/jcpp-1.4.14.jar:                                  #
#  +--------------------------------------+                         #
#  |  Loaded by  'quilted_fabric_loader'  |                         #
#  |  Name     = 'jcpp'                   |                         #
#  |  ID       = 'org_anarres_jcpp'       |                         #
#  |  Version  = '1.4.14'                 |                         #
#  |  LoadType = IF_POSSIBLE              |                         #
#  +--------------------------------------+                         #
#                                                                   #
#####################################################################

<mods>\memoryleakfix-fabric-1.17+-1.0.0.jar:
#########################################################
#  Loaded by  'quilted_fabric_loader'                   #
#  Name     = 'Memory Leak Fix'                         #
#  ID       = 'memoryleakfix'                           #
#  Version  = '1.0.0'                                   #
#  LoadType = IF_POSSIBLE                               #
#  Depends on 'fabricloader' [0.14.11, ∞)               #
#                                                       #
#  Contained Jars (1):                                  #
#                                                       #
#  /META-INF/jars/mixinextras-fabric-0.2.0-beta.6.jar:  #
#  +-------------------------------------------------+  #
#  |  Loaded by  'quilted_fabric_loader'             |  #
#  |  Name     = 'MixinExtras'                       |  #
#  |  ID       = 'com_github_llamalad7_mixinextras'  |  #
#  |  Version  = '0.2.0-beta.6'                      |  #
#  |  LoadType = IF_POSSIBLE                         |  #
#  |  Depends on 'fabricloader' [0.14.11, ∞)         |  #
#  +-------------------------------------------------+  #
#                                                       #
#########################################################

<mods>\quiltgoslightlyfasterlol-0.0.3.jar:
###########################################
#  Loaded by  'quilt_loader'              #
#  Name     = 'quiltgoslightlyfasterlol'  #
#  ID       = 'quiltgoslightlyfasterlol'  #
#  Version  = '0.0.3'                     #
#  LoadType = IF_REQUIRED                 #
###########################################

<mods>\smoothmenu-1.0.0.jar:
############################################
#  Loaded by  'quilted_fabric_loader'      #
#  Name     = 'Smooth Menu'                #
#  ID       = 'smoothmenu'                 #
#  Version  = '1.0.0'                      #
#  LoadType = IF_POSSIBLE                  #
#  Depends on 'fabricloader' [0.14.17, ∞)  #
#  Depends on 'minecraft' (-∞, ∞)          #
#  Depends on 'java' [17, ∞)               #
############################################

<mods>\[更好的树叶渲染优化] CullLessLeaves-1.0.1.jar:
#########################################################
#  Loaded by  'quilted_fabric_loader'                   #
#  Name     = 'Cull Less Leaves'                        #
#  ID       = 'cull-less-leaves'                        #
#  Version  = '1.0.1'                                   #
#  LoadType = IF_POSSIBLE                               #
#  Depends on 'fabricloader' [0.13.0, ∞)                #
#  Depends on 'minecraft' (-∞, ∞)                       #
#  Depends on 'java' [17, ∞)                            #
#                                                       #
#  Contained Jars (1):                                  #
#                                                       #
#  /META-INF/jars/mixinextras-0.0.9.jar:                #
#  +-------------------------------------------------+  #
#  |  Loaded by  'quilted_fabric_loader'             |  #
#  |  Name     = 'mixinextras'                       |  #
#  |  ID       = 'com_github_llamalad7_mixinextras'  |  #
#  |  Version  = '0.0.9'                             |  #
#  |  LoadType = IF_POSSIBLE                         |  #
#  +-------------------------------------------------+  #
#                                                       #
#########################################################

<mods>\[疾速加载] dashloader-4.1.3+1.18.jar:
##################################################
#  Loaded by  'quilted_fabric_loader'            #
#  Name     = 'DashLoader'                       #
#  ID       = 'dashloader'                       #
#  Version  = '4.1.3+1.18'                       #
#  LoadType = IF_POSSIBLE                        #
#  Depends on 'fabricloader' [0.11.3, ∞)         #
#  Depends on 'minecraft' [1.18, 1.19)           #
#  Depends on 'java' [16, ∞)                     #
#  Breaks  on 'sodium' (-∞, 0.1.0]               #
#                                                #
#  Contained Jars (3):                           #
#                                                #
#  /META-INF/jars/Hyphen-0.2.2.jar:              #
#  +-----------------------------------------+   #
#  |  Loaded by  'quilted_fabric_loader'     |   #
#  |  Name     = 'Hyphen'                    |   #
#  |  ID       = 'dev_quantumfusion_hyphen'  |   #
#  |  Version  = '0.2.2'                     |   #
#  |  LoadType = IF_POSSIBLE                 |   #
#  +-----------------------------------------+   #
#                                                #
#  /META-INF/jars/Taski-1.1.0.jar:               #
#  +----------------------------------------+    #
#  |  Loaded by  'quilted_fabric_loader'    |    #
#  |  Name     = 'Taski'                    |    #
#  |  ID       = 'dev_quantumfusion_taski'  |    #
#  |  Version  = '1.1.0'                    |    #
#  |  LoadType = IF_POSSIBLE                |    #
#  +----------------------------------------+    #
#                                                #
#  /META-INF/jars/zstd-jni-1.5.2-2.jar:          #
#  +------------------------------------------+  #
#  |  Loaded by  'quilted_fabric_loader'      |  #
#  |  Name     = 'zstd-jni'                   |  #
#  |  ID       = 'com_github_luben_zstd-jni'  |  #
#  |  Version  = '1.5.2-2'                    |  #
#  |  LoadType = IF_POSSIBLE                  |  #
#  +------------------------------------------+  #
#                                                #
##################################################

<mods>\[钠] sodium-fabric-mc1.18.2-0.4.1+build.15.jar:
##############################################################################
#  Loaded by  'quilted_fabric_loader'                                        #
#  Name     = 'Sodium'                                                       #
#  ID       = 'sodium'                                                       #
#  Version  = '0.4.1+build.15'                                               #
#  LoadType = IF_POSSIBLE                                                    #
#  Depends on 'fabricloader' [0.12.0, ∞)                                     #
#  Depends on 'fabric-rendering-data-attachment-v1' [0.1, ∞)                 #
#  Depends on 'fabric-rendering-fluids-v1' [0.1, ∞)                          #
#  Breaks  on 'optifabric' (-∞, ∞)                                           #
#  Breaks  on 'canvas' (-∞, ∞)                                               #
#                                                                            #
#  Contained Jars (5):                                                       #
#                                                                            #
#  /META-INF/jars/fabric-api-base-0.4.3+d7c144a8d2.jar:                      #
#  +----------------------------------------+                                #
#  |  Loaded by  'quilted_fabric_loader'    |                                #
#  |  Name     = 'Fabric API Base'          |                                #
#  |  ID       = 'fabric-api-base'          |                                #
#  |  Version  = '0.4.3+d7c144a8d2'         |                                #
#  |  LoadType = IF_POSSIBLE                |                                #
#  |  Depends on 'fabricloader' [0.4.0, ∞)  |                                #
#  +----------------------------------------+                                #
#                                                                            #
#  /META-INF/jars/fabric-rendering-data-attachment-v1-0.3.6+d7c144a8d2.jar:  #
#  +------------------------------------------------------+                  #
#  |  Loaded by  'quilted_fabric_loader'                  |                  #
#  |  Name     = 'Fabric Rendering Data Attachment (v1)'  |                  #
#  |  ID       = 'fabric-rendering-data-attachment-v1'    |                  #
#  |  Version  = '0.3.6+d7c144a8d2'                       |                  #
#  |  LoadType = IF_POSSIBLE                              |                  #
#  |  Depends on 'fabricloader' [0.4.0, ∞)                |                  #
#  |  Depends on 'fabric-api-base' (-∞, ∞)                |                  #
#  +------------------------------------------------------+                  #
#                                                                            #
#  /META-INF/jars/fabric-rendering-fluids-v1-2.0.1+54e5b2ecd2.jar:           #
#  +---------------------------------------------+                           #
#  |  Loaded by  'quilted_fabric_loader'         |                           #
#  |  Name     = 'Fabric Rendering Fluids (v1)'  |                           #
#  |  ID       = 'fabric-rendering-fluids-v1'    |                           #
#  |  Version  = '2.0.1+54e5b2ecd2'              |                           #
#  |  LoadType = IF_POSSIBLE                     |                           #
#  |  Depends on 'fabricloader' [0.4.0, ∞)       |                           #
#  |  Depends on 'fabric-api-base' (-∞, ∞)       |                           #
#  +---------------------------------------------+                           #
#                                                                            #
#  /META-INF/jars/fabric-resource-loader-v0-0.4.16+55dca1a4d2.jar:           #
#  +--------------------------------------------+                            #
#  |  Loaded by  'quilted_fabric_loader'        |                            #
#  |  Name     = 'Fabric Resource Loader (v0)'  |                            #
#  |  ID       = 'fabric-resource-loader-v0'    |                            #
#  |  Version  = '0.4.16+55dca1a4d2'            |                            #
#  |  LoadType = IF_POSSIBLE                    |                            #
#  |  Depends on 'fabricloader' [0.4.0, ∞)      |                            #
#  +--------------------------------------------+                            #
#                                                                            #
#  /META-INF/jars/joml-1.10.2.jar:                                           #
#  +--------------------------------------+                                  #
#  |  Loaded by  'quilted_fabric_loader'  |                                  #
#  |  Name     = 'joml'                   |                                  #
#  |  ID       = 'org_joml_joml'          |                                  #
#  |  Version  = '1.10.2'                 |                                  #
#  |  LoadType = IF_POSSIBLE              |                                  #
#  +--------------------------------------+                                  #
#                                                                            #
##############################################################################

---- end of report ----

**Comment by TheGlitch76** [comment]
Auto ModPack and Quilt Go Slightly Faster are incompatible, you must remove one (I'd recommend removing Quilt Go Slightly Faster, but it's up to you.)

We're working on improving error messages like this soon.

In the future, consider using our [forum](https://forum.quiltmc.org/c/support/9) or [Discord](https://discord.quiltmc.org)--you'll get faster and better support there.
