### ISSUE TITLE
Quilt crash

### ISSUE THREAD

**Issue by Mafy-17** [QuiltMC/quilt-loader#302]
log: https://mclo.gs/OMkgVKp
[crash-2023-05-07_17.56.23-client.txt](https://github.com/QuiltMC/quilt-loader/files/11415433/crash-2023-05-07_17.56.23-client.txt)

**Comment by TheGlitch76** [comment]
Your version of "NotEnoughAnimations" is incompatible with the version of ModMenu you have installed.
Try updating NotEnoughAnimations. If the issue still happens, contact the author of it for help.


Also, in the future, consider using our [forum](https://forum.quiltmc.org/c/support/9) or [Discord](https://discord.quiltmc.org)--you'll get faster and better support there.
