### ISSUE TITLE
unhandled crash error

### ISSUE THREAD

**Issue by EzeGB** [QuiltMC/quilt-loader#304]
[crash-2023-05-07_16.09.39.7230-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/11415926/crash-2023-05-07_16.09.39.7230-quilt_loader.txt)

**Comment by EzeGB** [comment]
It seems to be related to versions of mods, but it's not specified which one

**Comment by eristhea** [comment]
your modmenu is out of date, updating it to the latest version should fix your issue
in the future please put support requests on the discord or the forum!

**Comment by TheGlitch76** [comment]
Update ModMenu to version 5.0 or later
