### ISSUE TITLE
Fabric's incompatible mods tag shows up as "Unhandled Crash Error" on quilt

### ISSUE THREAD

**Issue by cootshk** [QuiltMC/quilt-loader#306]
Example log: https://mclo.gs/FdVfBCH

(This should say `Update world-host to a version that is compatible with modmenu version 6.1.0-rc.4, or update modmenu to a version that is compatible with world-host version 0.3.4`)

**Comment by TheGlitch76** [comment]
I've opened #309 to consolidate all of these issues.
