### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SecretGamerV071** [QuiltMC/quilt-loader#307]
https://mclo.gs/M6odo9c

Please help

**Comment by TheGlitch76** [comment]
Remove Fabric API; you don't need it when you have Quilted Fabric API installed.

We're working on improving error messages like this soon.

In the future, consider using our [forum](https://forum.quiltmc.org/c/support/9) or [Discord](https://discord.quiltmc.org)--you'll get faster and better support there.
