### ISSUE TITLE
Another Crash

### ISSUE THREAD

**Issue by SecretGamerV071** [QuiltMC/quilt-loader#308]
https://mclo.gs/SjUWhCs

**Comment by TheGlitch76** [comment]
Chat patches and MoreChatHistory are incompatible; you must use one and remove the other.

We're working on improving error messages like this soon.

In the future, consider using our [forum](https://forum.quiltmc.org/c/support/9) or [Discord](https://discord.quiltmc.org)--you'll get faster and better support there.
