### ISSUE TITLE
More help?

### ISSUE THREAD

**Issue by SecretGamerV071** [QuiltMC/quilt-loader#310]
https://mclo.gs/YEU9DPs

**Comment by Fnige** [comment]
> `[17:47:58] [main/ERROR]: Mixin prepare for mod organized_tabs failed preparing ExampleMixin in modid.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found`

Organised Tabs?

**Comment by SecretGamerV071** [comment]
Not a mod I have installed

**Comment by Fnige** [comment]
Better tabs is its name

**Comment by eristhea** [comment]
this tracker is for quilt loader issues, not support. you can get help on our forum or discord!
