### ISSUE TITLE
Error: Cannot invoke "org.quiltmc.loader.impl.gui.QuiltForkComms.send(org.quiltmc.loader.api.LoaderValue)" because "org.quiltmc.loader.impl.gui.QuiltFork.COMMS" is null

### ISSUE THREAD

**Issue by luftwafflezz** [QuiltMC/quilt-loader#318]
I'm trying to launch a server with a bunch of mods in it but occasionally when I add new mods it gives me this error: `Cannot invoke "org.quiltmc.loader.impl.gui.QuiltForkComms.send(org.quiltmc.loader.api.LoaderValue)" because "org.quiltmc.loader.impl.gui.QuiltFork.COMMS" is null`

Here is the crash report: 
[crash-2023-06-12_11.58.38.7230-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/11725415/crash-2023-06-12_11.58.38.7230-quilt_loader.txt)

This is the server version of a modpack I made, with performance mods differing in the serverpack and the clientpack. I added the same gameplay-changing mods to both packs and the clientpack worked but the server didn't.

I had a similar error before but that was because I accidentally had the Fabric API and QFAPI in the folder at the same time. I removed Fabric API and the server launched normally.

**Comment by AlexIIL** [comment]
Okay this should be fixed in 0.19.1-beta.2 - can you retry?

**Comment by luftwafflezz** [comment]
It did not work. Here's the new crash report 
[crash-2023-06-13_11.16.23.6451-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/11736472/crash-2023-06-13_11.16.23.6451-quilt_loader.txt)

**Comment by AlexIIL** [comment]
It looks like `ad_astra` requires `resourcefullib`, which doesn't seem to be in your mods folder - can you try adding it?

**Comment by luftwafflezz** [comment]
Server launched successfully, thank you. I wish it would tell you about the missing dependency. I can't read Java stack. Anyway, thank you for your help @AlexIIL.

**Comment by AlexIIL** [comment]
I think it does in the crash report? (Line 6 - `Ad Astra requires version [1.1.23, ∞) of resourcefullib, which is missing!`) I guess that means it doesn't tell you in the server console :/

**Comment by luftwafflezz** [comment]
Oh, I guess I should have bothered trying to read it :\
