### ISSUE TITLE
The "restrict_game_versions" Option Doesn't Work

### ISSUE THREAD

**Issue by jetblackrx89** [QuiltMC/quilt-loader#320]
The "restrict_game_versions" option doesn't appear to function as documented [here](https://github.com/QuiltMC/quilt-loader/wiki/Mod-Loading-Behaviour#loading-from-folders).

Attached is a crashlog where quilt-loader-0.19.0-1.20 detects duplicate mods because it's trying to look inside the 1.19.4 folder that also has quilt-compatible mods, it detects those as a duplicate and crashes.

I tried naming the folder the following and none worked:
- 1.20
- 1.20.0
- 1.20-0.19.0
- quilt-loader-1.20
- quilt-loader-0.19.0-1.20

My hunch is that since it is detecting "Version  = '1.20'" as seen in the crash logs, "1.20" should have worked, but there's a bug in this logic maybe for the sub-version parsing?

/src/main/java/org/quiltmc/loader/impl/plugin/QuiltPluginManagerImpl.java
```
char first = name.isEmpty() ? ' ' : name.charAt(0);
if ('0' <= first && first <= '9' || V1ModMetadataReader.isConstraintCharacter(first)) {
         // Might be a game version
        if (config.restrictGameVersions && gameVersion != null) {
                     // TODO: Support "1.12.x" type version parsing...
		    for (String sub : name.split(" ")) {
				if (sub.isEmpty()) {
					continue;
				}

		    	       char c = sub.charAt(0);

				if ('0' <= c && c <= '9') {
					sub = "=" + sub;
				}
```

Thanks!

quilt-loader.txt
```
#Quilt-loader configuration: https://github.com/QuiltMC/quilt-loader/wiki/Configuration-options
#Sat Jun 10 01:59:16 EDT 2023
restrict_game_versions=true
always_show_mod_state_window=false
load_sub_folders=true
```

[crash-2023-06-13_22.54.53.4579-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/11741216/crash-2023-06-13_22.54.53.4579-quilt_loader.txt)

**Comment by AlexIIL** [comment]
Can you retry with `0.19.1-beta.3`? I just [fixed a bug](https://github.com/QuiltMC/quilt-loader/commit/63fa871b06d8c3dbce0cfac196eb7134800a782e) related to this where versions are interpreted the same as in dependencies - so `1.20` is read as `^1.20` rather than `=1.20`. (As such if you created a folder named `1.21` it should be excluded, since `^1.21` means *"between `1.21` and less than `2.0`"*

**Comment by jetblackrx89** [comment]
Yep, beta 3 fixed it. Thanks!
