### ISSUE TITLE
Invalid `fabric.mod.json` for Plushie Mod only on QL 0.19.1 and above

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilt-loader#322]
**MC** 1.19.2
**QL** 0.19.1+
**[Plushie Mod](https://www.curseforge.com/minecraft/mc-mods/plushie-mod/files/3827209)** v1.2

To reproduce simply install the mod and FAPI/QFAPI on Quilt Loader 0.19.1 or higher and start the game. Reverting to Quilt loader 0.19.0 lets the game start.

Logs: https://gist.github.com/SplendidAlakey/345f1af90d08e8a43fab3dea08a9eccb

**Comment by AlexIIL** [comment]
It looks like it's failing to parse `Cake Mod by Link4real` as a version predicate, which seems somewhat understandable since none of those 4 words are really versions.

```json
  "suggests": {
    "cakemod": "Cake Mod by Link4real"
  }
```

This probably would also happen with non-overlapping version predicates, like `"suggests": { "cakemod": "<1.2 >1.5" }`

**Comment by SplendidAlakey** [comment]
Fixed in 0.19.2.
