### ISSUE TITLE
Disable beacon by default

### ISSUE THREAD

**Issue by ezra-351** [QuiltMC/quilt-loader#333]
"privacy by default" is a sentiment i am sure nearly everyone that would've chosen to use quilt would agree with. making the beacon opt-out goes against what a large chunk of what the community stands for. we do not want to have potential sponsors or likewise things be prioritized over our standards.

i can say that i personally would gladly opt in, given that the beacon were non-invasive to my privacy and user experience. alternatively you could add a non-invasive opt-in checkbox to enable beacon in the quilt installer. this of course will result in a number not going up as much as it _could_, however, a large number of the people who wouldn't check the box are simply people who don't want to be tracked, and would opt out if they knew about the beacon, and/or opting out was much more convenient. it's not fair to these people to track them when they do not wish to be tracked.

**Comment by eristhea** [comment]
hi!
I'm sure you've read all our discussions about this, but disabled-by-default defeats the purpose:
- it means we don't have any semblance of an MAU number: we have a number of people who care enough to click the checkbox. this doesn't tell us much about our overall usage

we've also been very careful to keep this private! no data is stored beyond "number go up", and nothing is even sent beyond the bare necessities for a web request. if you have any suggestions on how the privacy could be improved, that's fantastic! However, disabling by default is the one thing we can't do.

**Comment by ezra-351** [comment]
my point is, the people who don't "care enough to click the checkbox" are the people who wouldn't want to be tracked if they knew they were, or if it was easier for them to opt out.

**Comment by Aquaeyes** [comment]
Perhaps make it far more obvious how it can be disabled on first startup or the like? Currently adding a JVM flag, etc. is required, and I'd feel a lot better about it if there was an easy way for a user to just click and disable it if they want to, after knowing that only the number of unique users is incremented - informed consent is important after all!

**Comment by ezra-351** [comment]
offering a checkbox in the installer that's enabled by default would be leagues better than requiring a jvm flag. however it doesn't change the fact that it's still a community-second design. this also creates issues with launchers that implement a quilt installer, would they provide the same functionality? although it's ultimately an issue for launcher devs, the nice thing to do would be to not track users if they don't provide a checkbox.

**Comment by AlexIIL** [comment]
Obsoleted by [RFC#84](https://github.com/QuiltMC/rfcs/issues/84)
