### ISSUE TITLE
Request to Update to Fabric API 0.86.0

### ISSUE THREAD

**Issue by jetblackrx89** [QuiltMC/quilt-loader#337]
Fabric API was updated to 0.86.0 on July 18th, and some mods like Continuity are starting to require it, leading to launcher errors. The Quilt dev team might already be aware, but I am filing this just in case, since I haven't seen it mentioned on an issue trackers or forums.

**Comment by Redfan2** [comment]
This is already a known problem and there is a Pull Request for this in the works. You did nothing wrong by reporting it. Because of the way Quilt is built, this is not classified as an Error with the Loader, which is why you didn‘t notice it. Duplicate of QuiltMC/quilted-fabric-api#111

**Comment by jetblackrx89** [comment]
Thanks! I missed that. Closing this one out.
