### ISSUE TITLE
Quilt crashes mentioning a beacon.

### ISSUE THREAD

**Issue by MagmaSlime123** [QuiltMC/quilt-loader#343]
Title. Whatever this 'beacon' is, MC refuses to start up. Sometimes with mods, sometimes without.

https://mclo.gs/pFIF6P6

![image](https://github.com/QuiltMC/quilt-loader/assets/51277766/898cf573-3398-45d9-8d1c-0e3374b17a2e)

Logs have mods and other info.

**Comment by OroArmor** [comment]
This is a sodium problem. The missing beacon is just a warning.

**Comment by MagmaSlime123** [comment]
It crashes the game on startup.
