### ISSUE TITLE
Mod Menu Freeze with Quilt

### ISSUE THREAD

**Issue by ItsSunnyMonster** [QuiltMC/quilt-loader#344]
# To Reproduce
* Install Quilt 0.19.2 (latest at the time of writing), Minecraft 1.20.1 and these mods: (seem to be Zoomify that is causing the crash only on Quilt and not on fabric)
<img width="574" alt="image" src="https://github.com/QuiltMC/quilt-loader/assets/100400733/41104e16-09c9-44d8-88ae-0be83b5fafae">

* Open Minecraft and press "Mods" on the home screen

## Results
* The screen would freeze but interactions still seemed to happen
    * Click in random places and sometimes you can hear the click sound as if a button has been pressed
    * Load into a world, hit escape and press "Mods" then press escape twice and the cursor would be captured and you will hear game sounds
* Pressing the x button on the window does nothing and the only way to close Minecraft is to kill the process

## Logs
[https://pastebin.com/ndUGTXDm](https://pastebin.com/ndUGTXDm)

# Does not reproduce with fabric
* Create a new Minecraft 1.20.1 instance and install Fabric 0.14.22 (latest at the time of writing)
* Install these mods:
<img width="574" alt="image" src="https://github.com/QuiltMC/quilt-loader/assets/100400733/bbd11604-76b5-4701-ad16-10ad040086cc">

* Open Minecraft and press "Mods" on the home screen

## Results
Mod Menu does not freeze as expected.

# Other information
**System:** Macbook Pro M1 with 8-core CPU and 14-core GPU
**Java Version:** Eclipse Temurin JDK 18 (JDK 17 was causing problems with another mod)
**Launcher:** Prism Launcher

Please let me know if any other information is needed.

My apologies if this is not an appropriate place to report this issue, and it would be appreciated if you could point me to a better place to post it.

**EDIT:** I have made sure that the issue is still present with Java 17 (the recommended version of java for 1.20.1

**Comment by rinOfTheStars** [comment]
Was able to reproduce—this is likely an issue with the config screen generated by YACL for Zoomify? Going to actually stick this in a dev env. and see what's going on under the hood via a debugger if I can...

**Comment by rinOfTheStars** [comment]
Something funky is going on involving QKL (a lot of `ClassNotFoundException`s related to Kotlin classes are being thrown), going to refer this to the maintainers for that project

**Comment by ItsSunnyMonster** [comment]
Thank you very much!

**Comment by rinOfTheStars** [comment]
Issue isn't related to Kotlin at all, and is an issue with YACL somewhere.

**Comment by rinOfTheStars** [comment]
https://github.com/isXander/YetAnotherConfigLib/issues/101

**Comment by ItsSunnyMonster** [comment]
Since the other issue has been closed, I think it is safe to close this one. I don't have much time to check if the issue still reproduces on my end but if I reproduce this issue later I will reopen it. Thank you very much for your help!
