### ISSUE TITLE
Quilt tries but fails miserably to contact "the beacon" at each launch

### ISSUE THREAD

**Issue by k0nstruct** [QuiltMC/quilt-loader#345]
What kind of wizardry is this?
![image](https://github.com/QuiltMC/quilt-loader/assets/95828007/efddb805-3f5b-45e8-b791-794c335da772)
Is minecraft real? That's it. Theory confirmed.

**Comment by TheGlitch76** [comment]
This will be fixed in a couple days!

**Comment by TheGlitch76** [comment]
It's not harmful, so you can safely ignore it for now.

**Comment by k0nstruct** [comment]
Alright, thanks! Jokes aside, make sure you warn users with a concise log message if you're running analytics!

**Comment by TheGlitch76** [comment]
We currently intend to remove it entirely.
