### ISSUE TITLE
ERROR ERROE ERROR!!!!!

### ISSUE THREAD

**Issue by crue1ix** [QuiltMC/quilt-loader#347]
Every time i open quilt it keeps saying that something went very wrong while opening the mods. Please fix this!!!

![Screen Shot 2023-08-16 at 6 09 50 PM](https://github.com/QuiltMC/quilt-loader/assets/142454853/ab8d09b5-1777-47ff-8872-77fb8e6b4892)
![Screen Shot 2023-08-16 at 6 10 31 PM](https://github.com/QuiltMC/quilt-loader/assets/142454853/710c7618-9bf5-4500-8c7a-7b7dd66717ab)

**Comment by eristhea** [comment]
hi, please click the "open report" or "copy report" buttons to get the information that we need in order to fix this!

**Comment by heipiao233** [comment]
Hi! Please read [this](http://www.catb.org/~esr/faqs/smart-questions.html). I'm not punishing you, but trying to make others to help you. Note that the word `hacker` in the article doesn't mean someone bad.

**Comment by eristhea** [comment]
i'm closing this issue for now as there's not enough information available to help. feel free to reopen!
