### ISSUE TITLE
Minecraft can't start I had a diffrent error and now it has changed

### ISSUE THREAD

**Issue by unatried** [QuiltMC/quilt-loader#349]
I was using Minecraft fabric but realized that quilt is a better option because most of the mods I was using recommended quilt. After a couple of launches, I had an error where I had to add more ram which I fixed afterward, I got this error and here is my crash report:

[Crash Report](https://pastebin.com/gJ8hwj1G)

Mods are in the crash report
RAM: 8.00 GB (7.82 GB usable) Minecraft uses 4 GB
GPU: Intel HD Graphics 4000
CPU: Intel® Core™ i5-3320M CPU @ 2.60GHz 2.60 GHz
Java Executable: C:\Program Files\Java\jdk-20\javaw.exe

**Comment by AlexIIL** [comment]
You need to either report this to `mixinconflicthelper` (https://github.com/isXander/MixinConflictHelper) or remove `<mods>\MixinConflictHelper-1.2.0.jar`.

**Comment by unatried** [comment]
First I removed both, then MixinConflictHelper only and then SpASM only. When I updated sodium and compiled sodium extra for sodium 0.5.2 which is available [here](https://github.com/ZugCodez/sodium-extra-fabric/tree/1.20.x/dev-1) I got this error ![Error](https://github.com/QuiltMC/quilt-loader/assets/103455203/1ac308a3-ef80-403d-8808-8c8b2b70ed90) there was no update for reeses sodium options. my new [crash repot](https://pastes.io/cgkebdyana) (paste bin doesnt allow over 512kb) and my [log](https://pastes.io/omalloiiyd)

**Comment by unatried** [comment]
I changed a couple of mods again and It doesnt  process some source files for some reason I had this before but I restared and it solved itself now it doesnt

**Comment by unatried** [comment]
I am going to close this because I am restarting my modpack
