### ISSUE TITLE
match QM conventions in api methods

### ISSUE THREAD

**Issue by eristhea** [QuiltMC/quilt-loader#361]
`ModContainer#metadata` and `ModContainer#rootPath` in `org.quiltmc.loader.api.ModContainer` violate the QM convention of always prefacing getters with `get` unless they're part of a record. this should be fixed to ensure all quilt tooling has a consistent naming scheme!

**Comment by AlexIIL** [comment]
`ModMetadata`, `Version`, `ModLicense`, `ModContributor`, `ModDependency`, `ProvidedMod`, `LoaderValue` also all violate this convention. But since we don't have plugins yet we can break them (and add default methods for backwards compat) so it's definitely possible for us to change this.

**Comment by OroArmor** [comment]
Personally im not a huge fan of `.get` and I think more modern APIs, like loader, can go without.

**Comment by TheGlitch76** [comment]
For context, Loader uses this naming convention because Java is explicitly going that way with records and pretty much all new APIs.

**Comment by eristhea** [comment]
sounds good then!
