### ISSUE TITLE
i don't know what is causing it

### ISSUE THREAD

**Issue by liamwerk7676** [QuiltMC/quilt-loader#364]
when i install create extra modpack and replace fabric Api with quilt Api and fabric Kotlin with quilt Kotlin it just crashes here is my crash log
[crash-2023-09-10_16.46.45-client.txt](https://github.com/QuiltMC/quilt-loader/files/12568487/crash-2023-09-10_16.46.45-client.txt)

**Comment by eristhea** [comment]
> Caused by: java.lang.IllegalStateException: Quilt Loader detected.
You appear to be using the Fabric version of WTHIT with Quilt, which is unsupported.
Please use a version of WTHIT that specifically made for Quilt instead.

in the future please request support on the forum or the discord!

**Comment by liamwerk7676** [comment]
> > Caused by: java.lang.IllegalStateException: Quilt Loader detected.
> > You appear to be using the Fabric version of WTHIT with Quilt, which is unsupported.
> > Please use a version of WTHIT that specifically made for Quilt instead.
> 
> in the future please request support on the forum or the discord!

thank you so mutch this makes the modpack playable for me thank jou
