### ISSUE TITLE
Unable to launch 1.2.5 server with loader

### ISSUE THREAD

**Issue by LostLuma** [QuiltMC/quilt-loader#376]
Trying to use Quilt on Minecraft 1.2.5 (installed via ornithe installer) results in a crash:

Server Log: https://files.lostluma.net/D24Olt.txt
Crash Report: https://files.lostluma.net/n9ktHM.txt

Same issue also affects Fabric: https://github.com/FabricMC/fabric-loader/issues/819

**Comment by AlexIIL** [comment]
I've re-opened this until the fix is actually pushed, and tested.

**Comment by LostLuma** [comment]
I've tested this now on 0.21.2-beta.4 and can confirm it works, thank you once again! 🦫
