### ISSUE TITLE
Load mods from subfolders

### ISSUE THREAD

**Issue by Reoseah** [QuiltMC/quilt-loader#38]
This will allow modpack makers and users to organize their mods however they want, e.g. put optimization mods into their own subfolder like `mods/optimizations/...`

This is different from https://github.com/QuiltMC/quilt-loader/issues/15 as it just removes current limitation when searching for mods.

Currently Fabric/Quilt loader uses `1` for max depth, I suggest change it to `Integer.MAX_VALUE` in this line: https://github.com/QuiltMC/quilt-loader/blob/232e1741a3d65e4e384958cb2e18ea37b099eaf2/src/main/java/org/quiltmc/loader/impl/discovery/DirectoryModCandidateFinder.java#L58

**Comment by romangraef** [comment]
Maybe this could be coupled with the ability to exclude entire folders, either based on the hidden attribute, or based on a prefix dot, like for regular mod jars as well.

**Comment by Reoseah** [comment]
> Maybe this could be coupled with the ability to exclude entire folders, either based on the hidden attribute, or based on a prefix dot, like for regular mod jars as well.

Yeah, that makes sense, and hidden folders and folders starting with `.` can be some unknown shit that perhaps shouldn't be loaded. 

That could be achieved by overriding another method in the file visitor:
```java
@Override
public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
	if (dir.getFileName().toString().startsWith(".") || Files.isHidden(dir)) {
		return FileVisitResult.SKIP_SUBTREE;
	}
	return FileVisitResult.CONTINUE;
}
```

**Comment by WanderingCat27** [comment]
if the loader is designed similarly to fabric in grabbing file paths as candidates it might be difficult but it would be a nice feature to search zip files as well as folders makes modpacks simple and for solves, non technical users, the mistake I see a lot of sticking a zip in the mods folder.

**Comment by WanderingCat27** [comment]
> > Maybe this could be coupled with the ability to exclude entire folders, either based on the hidden attribute, or based on a prefix dot, like for regular mod jars as well.
> 
> 
> 
> Yeah, that makes sense, and hidden folders and folders starting with `.` can be some unknown shit that perhaps shouldn't be loaded. 
> 
> 
> 
> That could be achieved by overriding another method in the file visitor:
> 
> ```java
> 
> @Override
> 
> public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
> 
> 	if (dir.getFileName().toString().startsWith(".") || Files.isHidden(dir)) {
> 
> 		return FileVisitResult.SKIP_SUBTREE;
> 
> 	}
> 
> 	return FileVisitResult.CONTINUE;
> 
> }
> 
> ```

fabric already does this

**Comment by AlexIIL** [comment]
Zip support for modpacks is certainly an *interesting* idea, however it depends quite heavily on what the zip contains. For example downloading a modpack zip from curseforge doesn't actually contain the mods, and instead contains a list of files to download, plus overrides for configs, resourcepacks, and occasionally mods that aren't on curseforge. (However this doesn't apply to all zips - some modpack zips might only contain mod jar files).

Either way zip support is not the topic of this particular issue, and I think you should open a different issue if you want to continue to discuss this.

**Comment by WanderingCat27** [comment]
> Zip support for modpacks is certainly an *interesting* idea, however it depends quite heavily on what the zip contains. For example downloading a modpack zip from curseforge doesn't actually contain the mods, and instead contains a list of files to download, plus overrides for configs, resourcepacks, and occasionally mods that aren't on curseforge. (However this doesn't apply to all zips - some modpack zips might only contain mod jar files).
> 
> 
> 
> Either way zip support is not the topic of this particular issue, and I think you should open a different issue if you want to continue to discuss this.

i was mainly referring to zips of just mods. i put it here cause i thought it was similar in the concept of how the loader explores the mod folder but realize it is a concept unrelated to sub folders directly ill add a new issue tho cause i would love to see it implemented if possible

**Comment by TheGlitch76** [comment]
This behavior occurs by default in Loader 0.18, and also supports subfolders for specific versions or even version ranges. See here for the exact behavior:

https://github.com/QuiltMC/quilt-loader/blob/6afb2e0b00ee7c2b1810f586d19dc0c1835a662e/src/main/java/org/quiltmc/loader/impl/plugin/QuiltPluginManagerImpl.java#L1541
