### ISSUE TITLE
LambdaBetterGrass requires any version of "quilt_resource_loader" & "quilt_block_extensions"

### ISSUE THREAD

**Issue by Probreyene** [QuiltMC/quilt-loader#384]
I tried matching the mod mc version and used a version of Quilt available when the mod was released on August 11.
(Idk what im doing pls help)
[https://pastebin.com/8W0ZHzva](https://pastebin.com/8W0ZHzva)

**Comment by Akarys42** [comment]
Hello. You'll need to delete Fabric API from your mod folder and replace it by [QSL](https://modrinth.com/mod/qsl).
