### ISSUE TITLE
Mods require 0.15.1 or newer version of `fabricloader`

### ISSUE THREAD

**Issue by itsKhalidHossain** [QuiltMC/quilt-loader#391]
Game failed to launch. Many of the Fabric mods for Minecraft 1.20.4 require `fabricloader` 0.15.1. If requirements are not met, game crashes during launch.

Operating system: Windows 11, version 23H2
Minecraft: 1.20.4
Quilt: 0.22.0

Crash report:
[crash-2023-12-24_22.57.27.9631-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/13762424/crash-2023-12-24_22.57.27.9631-quilt_loader.txt)

**Comment by LlamaLad7** [comment]
Update quilt loader

**Comment by itsKhalidHossain** [comment]
Version 0.22.0 is the latest stable version of `quiltloader`. I am using the latest version.

**Comment by LlamaLad7** [comment]
The latest version is 0.23.0-beta.2

**Comment by itsKhalidHossain** [comment]
True. But that's _beta_ version, not the stable version.

**Comment by FirstMegaGame4** [comment]
but you can still use beta versions
if the latest fabric loader is not currently included in a stable release, it means that AlexIIL doesn't finished yet to implement it correctly

**Comment by itsKhalidHossain** [comment]
Naah. Too much work. Going back to Fabric instead.

**Comment by FirstMegaGame4** [comment]
???
wow
didn't know that changing a version was lot of work

**Comment by itsKhalidHossain** [comment]
It's a feature in my launcher. I can download preconfigured profile for any modloader, Fabric, Quilt or Forge. But it supports only the stable version of Quilt.

I can just simply choose the Fabric one instead of installing Quilt manually. All my mods work with fabric and quilt. Well, not right now, but they used to work on Quilt. I can just simply select the Fabric profile and launch the game, and it works just like that.
