### ISSUE TITLE
Game Crashes on Startup

### ISSUE THREAD

**Issue by IrisWasTaken1** [QuiltMC/quilt-loader#394]
Crash log [here](https://github.com/QuiltMC/quilt-loader/files/13816122/crash-2024-01-02_21.11.24.2821-quilt_loader.txt)

**Comment by OroArmor** [comment]
Rayon and Sodium Shadowy Path Blocks do not work with the sodium version you have installed.

1. Please read the crash reports before making them
2. This is not the place for support with mod problems. Issues on this repository are for issues with the loader itself, not crashes with mods. Please go to our discord for support.
3. Please use the same issue in the future and do not make multiple issues in rapid succession.

**Comment by IrisWasTaken1** [comment]
> Rayon and Sodium Shadowy Path Blocks do not work with the sodium version you have installed.
> 
> 1. Please read the crash reports before making them
> 2. This is not the place for support with mod problems. Issues on this repository are for issues with the loader itself, not crashes with mods. Please go to our discord for support.
> 3. Please use the same issue in the future and do not make multiple issues in rapid succession.

I read the crash report before making the issue, and couldn't figure out the issue. Also, disabling both mods and mods that require them shows the exact same error
