### ISSUE TITLE
Crash without any mods on SDK Launcher

### ISSUE THREAD

**Issue by CaesarSP** [QuiltMC/quilt-loader#408]
I'm using the temurin environment and the 0.24.5-beta5. I tried the other betas and they don't work, with newer minecraft versions also.
I though that the "beta" part might signal why, but I still think it might worth to look at. Sorry if it's a loss of time. 

**Log is pretty short:**

[log.txt](https://github.com/QuiltMC/quilt-loader/files/14320382/log.txt)

**Comment by AlexIIL** [comment]
Thanks for reporting this properly - this will fixed by #407, but otherwise you'll need to downgrade to 0.23.1 until it's merged.
