### ISSUE TITLE
NullPointerException while starting Quilt

### ISSUE THREAD

**Issue by Brosweer** [QuiltMC/quilt-loader#411]
If any mods are added, Quilt will crash, even though the modpack worked before. I tried changing loader version, api version, but nothing worked.
Log:
[crash-2024-03-13_22.05.19.9678-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/14594098/crash-2024-03-13_22.05.19.9678-quilt_loader.txt)

**Comment by OroArmor** [comment]
This is an old issue with Decorative Blocks.
