### ISSUE TITLE
what is this Reported exception thrown! net.minecraft.class_148: Rendering overlay. when using quilt loader

### ISSUE THREAD

**Issue by ff6f8d68** [QuiltMC/quilt-loader#416]
-----LOG-----
log: [https://mclo.gs/eqCUwae](https://mclo.gs/eqCUwae)
-----LOG END-----

-----MODS-----
[quilt fabric api](https://www.curseforge.com/minecraft/mc-mods/qsl)
[Expedition Airship mod for Minecraft](https://ko-fi.com/post/Expedition-Airship-mod-for-Minecraft-1-19-2-X7X0GY8M8#checkoutModal)
-----MODS END-----

 -----QUILT FABRIC API VERSION-----
4.0.0-beta.30
 -----QUILT FABRIC API VERSION END-----

 -----QUILT LOADER VERSION-----
0.24.0
 -----QUILT LOADER VERSION END-----

 -----MINECRAFT VERSION-----
1.19.2
 -----MINECRAFT VERSION END-----

**Comment by eristhea** [comment]
this tracker is for quilt loader issues, not support. you can get help on our forum or discord!
