### ISSUE TITLE
Regression: Internal Error in dev environment when running with an empty (dummy) mod

### ISSUE THREAD

**Issue by anonymous123-code** [QuiltMC/quilt-loader#417]
This did not happen in loader 0.22.0. It apparently happens because newer versions expect some META-INF files relating to if the mod has to be remapped.
## Reproduction
1. Clone the template mod repo
2. Run runClient once to generate the run directory
3. Drop in a jar file containing only 
[quilt.mod.json](https://github.com/QuiltMC/quilt-loader/files/14825953/quilt.mod.json)
4. Run the client again.
5. Observe the following crash: 
[crash-2024-04-01_17.44.47.7103-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/14825959/crash-2024-04-01_17.44.47.7103-quilt_loader.txt)

**Comment by AlexIIL** [comment]
Can you retry with `0.25.0-beta.1`? I think I encountered this issue and quietly fixed it in [commit 1c74011 Fix annotations not applying properly to packages.](https://github.com/QuiltMC/quilt-loader/commit/1c740110454212dfa98c7a8b469491068eaedef5#diff-261c816c6787c6659fd600cff125513dd71d13c9a7551a660ec41ed38486b240)

**Comment by anonymous123-code** [comment]
It works there, thanks!
