### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by pavelbat3** [QuiltMC/quilt-loader#422]
launcher error:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'autocomplete'!

log:
[latest.log](https://github.com/QuiltMC/quilt-loader/files/15014777/latest.log)
debug log:
[debug.log](https://github.com/QuiltMC/quilt-loader/files/15014779/debug.log)

**Comment by OroArmor** [comment]
Mixin conflict between essential and better ui scale.

**Comment by pavelbat3** [comment]
Close it fully because i found the problem
