### ISSUE TITLE
Add an option to allow disable DelegatingUrlStreamHandlerFactory.

### ISSUE THREAD

**Issue by heipiao233** [QuiltMC/quilt-loader#424]
I'm developing a `QuiltLauncher` for launching Quilt Loader on ModLauncher. ModLauncher has their `ModularURLHandler`, and it's set as the factory before we can do anything. I currently uses Unsafe to clear `URL.factory`.
Could you please add this option? That's very helpful. Thank you.

**Comment by AlexIIL** [comment]
I don't know if it's even necessary, as I tried removing it and the game still launched. I'll add a system property `loader.disable_url_stream_factory` to disable it anyway though.
