### ISSUE TITLE
Zoomify and Controlify mods cannot start together because of a Quilted Fabric API quirk

### ISSUE THREAD

**Issue by NyaomiDEV** [QuiltMC/quilt-loader#425]
Relevant issue at the other end: https://github.com/isXander/Zoomify/issues/195

It seems as though the version parse method used by Quilt is ever so slightly different to induce some mods' code into behaving erratically.

Relevant calls:
https://github.com/isXander/Zoomify/blob/1.20/src/main/kotlin/dev/isxander/zoomify/integrations/IntegrationHelper.kt

**Comment by isXander** [comment]
QFAPI has nothing to do with this.
This is an issue with Quilt Loader itself.

**Comment by OroArmor** [comment]
Thanks for reminding me to transfer the issue

**Comment by NyaomiDEV** [comment]
> QFAPI has nothing to do with this. This is an issue with Quilt Loader itself.

@isXander Sorry, I tried! Sorry to you too @OroArmor :(

**Comment by isXander** [comment]
I'd assume that 2.x.x in Quilt does not match betas.

**Comment by isXander** [comment]
Can be closed?
