### ISSUE TITLE
Skip unknown mods windows

### ISSUE THREAD

**Issue by voidpointer0x00** [QuiltMC/quilt-loader#433]
Is there a way to skip the windown shown when there're files that are not mods? The `.dll` file just needs to be there :smile: 

![image](https://github.com/QuiltMC/quilt-loader/assets/43143315/d54cc7a0-a1e6-4a21-b0f7-a8bfb0496a9e)

**Comment by voidpointer0x00** [comment]
Just looked through the code, looks like there is no option to skip the menu

https://github.com/QuiltMC/quilt-loader/blob/3d8a6ac995b22d8b1e226b0e7145380a800d503c/src/main/java/org/quiltmc/loader/impl/QuiltLoaderImpl.java#L730

I guess I'll PR the feature :grin:

**Comment by AlexIIL** [comment]
Thanks!

**Comment by AlexIIL** [comment]
*(This issue will be closed when this is released fully)*

**Comment by eristhea** [comment]
this has been released fully in `0.26` :p
