### ISSUE TITLE
The gui-server encountered an error!

### ISSUE THREAD

**Issue by k0nstruct** [QuiltMC/quilt-loader#437]
Since the 0.25 beta, the gui server doesn't launch after crashes. I don't know why.

Steps to reproduce :
- Use Modrinth launcher and version 0.25 or later
- Have Kotlin and QFAPI
- Have an issue with mods during launch

Log message:

```
[20:10:59] [main/ERROR]:
 Crashed! The full crash report has been saved to C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\videos 2.1 (2)\crash-reports\crash-2024-06-10_20.10.59.7706-quilt_loader.txt
[20:10:59] [main/ERROR]:
 For more details see the full crash report file: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\videos 2.1 (2)\crash-reports\crash-2024-06-10_20.10.59.7706-quilt_loader.txt
[20:10:59] [Quilt IPC Handler 1/ERROR]:
 The gui-server encountered an error!
```

**Comment by anonymous123-code** [comment]
I encountered this issue as well.
I tested a bit. It works in 0.25.0-beta.2, and doesnt work in 0.25.0-beta.3, 0.25.0, and 0.25.6 (and some other betas)
A simple reproduction case is to load Minecraft 1.20.3 with quilted-fabric-api-8.0.0-alpha.6+0.91.6-1.20.2 and loader 0.26.0
Usually, it doesn't produce an additional crash report (Except the normal dependency resolution error log)
However, stdout contains some useful information:
https://mclo.gs/ut7wUzy

**Comment by anonymous123-code** [comment]
In other words https://github.com/QuiltMC/quilt-loader/commit/52e0ea16ef5210fc7b7ad8d47b432847a3f889df is the commit where the change happened

**Comment by k0nstruct** [comment]
I've had another go, it's really strange. Sometimes, the GUI does show up, and sometimes not, in the same 26.0 version. I'll have to find how to reproduce.

**Comment by eristhea** [comment]
according to #440, this has been fixed. please reopen if you can still reproduce on the latest versions!

**Comment by k0nstruct** [comment]
Sorry for the inactivity. It still happens somewhat but I'll have to confirm first. Thanks for all the hard work!
