### ISSUE TITLE
Found 1 unknown files

### ISSUE THREAD

**Issue by magmamir** [QuiltMC/quilt-loader#439]
![image](https://github.com/QuiltMC/quilt-loader/assets/136165761/d60d29b0-5267-4cca-ba19-8b416bb83861)
I use txt file in my mods directory to keep track of which mods have not been updated yet and should be added latter by me. In version 0.26 of loader every time I started Quilt, I got this error (it wasn't a thing in 0.24). I know about _Continue to Minecraft_ button, but this window still is very inconvenient. How can i disable it forever?

**Comment by AlexIIL** [comment]
I recommend against putting non-mod files in your mods folder, as loader plugins might try to load them.

However if you don't care about that (none exist now anyway) you can add the system property ` -Dloader.ignore_unsupported_mods=true ` to your JVM arguments to disable the window.

**Comment by magmamir** [comment]
Thank you, that worked. In my opinion that should be the default option until loader start actually using .txt files in /mods folder for something. Although, i think loader should always ignore .txt files and other weird for minecraft extension, and load only .jar and .json with special arguments (if Quilt adds loader plugins? in the future)
