### ISSUE TITLE
allow to specify path of server.jar via command line argument

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [QuiltMC/quilt-loader#441]
Just like the title says.

**Comment by AlexIIL** [comment]
You should be able to already - try adding `-Dloader.gameJarPath=custom_file.jar`?

**Comment by Zh40Le1ZOOB** [comment]
> -Dloader.gameJarPath=

Not work for server :(

**Comment by AlexIIL** [comment]
Can you show:

1. The folder you are launching the game from
2. The command line you are currently using?

**Comment by Zh40Le1ZOOB** [comment]
> Can you show:
> 
> 1. The folder you are launching the game from
> 2. The command line you are currently using?

I'm running NixOS so there are something different with normal Linux distros.

1.
/var/lib/minecraft
❯ ls
libraries  quilt-server-launch.jar

server.jar is a Nix derivation so it cannot be found manually.

2.
`java -jar quilt-server-launch.jar nogui -Dloader.gameJarPath=${pkgs.minecraft-server}/server.jar` < this will be replace with the real path by Nix.

output:
```
The Minecraft server .JAR is missing (/var/lib/minecraft/server.jar)!

Quilt's server-side launcher expects the server .JAR to be provided.
You can edit its location in quilt-server-launcher.properties.

Without the official Minecraft server .JAR, Quilt Loader cannot launch.
Exception in thread "main" java.lang.RuntimeException: Failed to setup Quilt server environment!
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:60)
Caused by: java.lang.RuntimeException: Missing game jar at /var/lib/minecraft/server.jar
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.setup(QuiltServerLauncher.java:86)
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:58)
```

**Comment by AlexIIL** [comment]
For some reason quilt loader is unable to find the file - does NixOS have a permissions system or something else that would prevent loader from being able to read the file?

**Comment by Zh40Le1ZOOB** [comment]
> For some reason quilt loader is unable to find the file - does NixOS have a permissions system or something else that would prevent loader from being able to read the file?

It's not permisson problem. I wrote a systemd service for minecraft server, the work directory is `/var/lib/minecraft`, so Quilt would find `server.jar` in `/var/lib/minecraft`. But I want to manage the service using Nix completely, so I can't put `server.jar` to `/var/lib/minecraft`, `server.jar` is actully not in a same directory with Quilt Loader. Insteadly, `server.jar` is located in Nix Store, so the only thing I need to do is specify path of `server.jar` via CLI args.

Is there any way to tell Quilt where to find `server.jar` or pass options in quilt-server-launcher.properties via CLI? Sorry to make misunderstanding.

**Comment by AlexIIL** [comment]
Oh, sorry, I should have noticed sooner - java system properties need to be earlier in the command line than the `-jar` - so if you change the command to `java -Dloader.gameJarPath=${pkgs.minecraft-server}/server.jar -jar quilt-server-launch.jar nogui` it should work.

**Comment by Zh40Le1ZOOB** [comment]
> Oh, sorry, I should have noticed sooner - java system properties need to be earlier in the command line than the `-jar` - so if you change the command to `java -Dloader.gameJarPath=${pkgs.minecraft-server}/server.jar -jar quilt-server-launch.jar nogui` it should work.

It works! Thank you very much!
