### ISSUE TITLE
Incompatibility with Traveler's Backpack Mod

### ISSUE THREAD

**Issue by Cvdusey** [QuiltMC/quilt-loader#442]
Hello! I am experiencing an issue where I am attempting to add the Traveler's Backpack (by Tiviacz1337) mod to a private modpack through Modrinth, but I am getting the Error Message "Invalid input: Unable to infer project type for input file," and am merely looking for a solution to this. Thank you for your time!

**Comment by eristhea** [comment]
unable to reproduce using traveler's backpack 9.6.3 on minecraft 1.20.6. can you share a full crash report?

**Comment by Cvdusey** [comment]
I'm not seeing anything int he logs...

**Comment by Cvdusey** [comment]
Here's the Error message as a screen shot in case it's helpful.
![Screenshot 2024-07-01 154523](https://github.com/QuiltMC/quilt-loader/assets/105762561/ec0636e9-5328-4d10-b41f-f6e58dbb961e)

**Comment by LostLuma** [comment]
This is a problem with the Modrinth App instead of Quilt Loader.  
You can see [that the error is created here in Theseus](https://github.com/modrinth/theseus/blob/8140db32dd992290b89652c6681c759f95f6eec1/theseus/src/state/profiles.rs#L605-L624) (on either end of the selection).

**Comment by Cvdusey** [comment]
Ok, thank you. I must say though, you guys are very fast at responding! =)
