### ISSUE TITLE
Fabric 0.16 support

### ISSUE THREAD

**Issue by IrisWasTaken1** [QuiltMC/quilt-loader#445]
When trying to load certain fabric mods on the latest QFAPI version, the following error pops up:
[Mod name] requires version 0.16.0 or any newer version of fabricloader, but only a different version is present: 0.15.11

Crash Log: https://paste.gg/p/anonymous/1b64db5acb784ca1989872a82c223fd9

**Comment by eristhea** [comment]
duplicate of #443
