### ISSUE TITLE
Minecraft 1.20.1 crashed on fabric modpack 

### ISSUE THREAD

**Issue by Azkapop** [QuiltMC/quilt-loader#449]
[crash-2024-08-18_14.46.26.8674-quilt_loader.txt](https://github.com/user-attachments/files/16647572/crash-2024-08-18_14.46.26.8674-quilt_loader.txt)
so minecraft just crashed

**Comment by Azkapop** [comment]
can anyone help?

**Comment by woodiertexas** [comment]
uhhhhh, i don't think loader github issues are the best place for getting support with crashes, i'd try getting support in the discord server.

also, its a good idea to upload crash reports to https://mclo.gs/ when getting support.

**Comment by OroArmor** [comment]
Install a newer version of Java. Specifically Java 17.
