### ISSUE TITLE
Quilt crash when crafting (using quilt api and quilt kotlin)

### ISSUE THREAD

**Issue by ToanAnh312** [QuiltMC/quilt-loader#459]
i just open the crafting table, shift-fast craft plank then SHIFT CLICK to get it, the game crash, this can be reproduce in my pc
![image](https://github.com/user-attachments/assets/cd6149f4-5e79-430e-a107-421fa709a444)
[crash-2024-12-08_16.32.20-client.txt](https://github.com/user-attachments/files/18051508/crash-2024-12-08_16.32.20-client.txt)
[crash-2024-12-08_16.21.07-client.txt](https://github.com/user-attachments/files/18051509/crash-2024-12-08_16.21.07-client.txt)
#

**Comment by ToanAnh312** [comment]
also mods that i use (all mod in 1.20.2): (alpha6 - latest verson, i changed to alpha5 after crash and IT WORKED)
![image](https://github.com/user-attachments/assets/b565cb95-6dab-4fa7-9f8c-7abd1bcbcc7e)

**Comment by ToanAnh312** [comment]
Video for reproduce xd
saturation effect i got from command
https://github.com/user-attachments/assets/1b149c4b-705c-4dc7-a1ef-d621961ee1c3

**Comment by OroArmor** [comment]
Yeah downgrading qfapi is the fix. There was a bug in alpha 6. i thought I released a new version but I guess I didn't.
