### ISSUE TITLE
Declare intermediate mappings in `quilt.mod.json`

### ISSUE THREAD

**Issue by TheGlitch76** [QuiltMC/quilt-loader#59]
This is a good first issue for anyone looking to dip in to contributing to Loader. If you are interested in getting this done, feel free to ask me questions at `glitch#3274` on the Toolchain Discord.

# The issue
Currently, Loader does not have a reliable way of telling what intermediate mappings were used when compiling a mod. This is a problem, because mods currently use the (legacy) Intermediary mappings, but in the future they will be compiled to Hashed.

## Motivation
We want to support Quilt mods compiled to Intermediary, even after we switch to Hashed, for two reasons:
- (major) We aren't sure when our toolchain will support compiling to Hashed, and we'd like to avoid unnecessarily breaking already compiled Quilt mods, especially since the infrastructure for remapping mods from intermediary to hashed will be present due to Fabric compatibility,
- (minor) Since (as mentioned above) we will be able to remap int -> hashed anyway, it would be nice to allow multi-loader jars (i.e. Fabric and Quilt) to use the same mapping set, to reduce file size and complexity in the build process.
    - *side note: Multi-loader jars are important to Quilt during the beta period, because it allows major mods to experiment with the new Quilt APIs without forcing their users onto an unknown, experimental, and unstable modloader.*
 
 # Proposed Solution
 This solution is intended to be as simple as possible, 
 ## QMJ Specification in RFC Repository
 Add a new, optional field to the `quilt_loader` field of the `quilt.mod.json`, named `intermediate_mappings`. It is a string value that defaults to `"hashed"`, but can be set to `"intermediary"`. 

 ## Implementation in Loader
### Parser
For now, we can simply implement a no-op in Loader that asserts that the `intermediate_mappings` field is set to `intermediary`. It should be read during mod parsing, and mod parsing should fail if:
- The value is unknown (something like "Error: Unknown intermediate mappings 'example'")
- The value is `hashed`, since we don't support it in Loader yet. This one should have a more user-friendly error message, directing the user to update Quilt Loader, since if we see this field we know that this is a mod from the future!
### Mod Metadata
The `InternalModMetadata` metadata interface should gain a new method,:
` String intermediateMappings()`
that would return the string read in the `quilt.mod.json`. For now, this can default to always return `intermediary` (see future steps below)

# Future Steps
- We will need to properly track the string given in the `quilt.mod.json` for `intermediate_mappings`,  instead of asserting that it exists and throwing the value away, so that it can be properly exposed to Loader. Bonus points if you implement it this way in your PR, but it's not required.
- In the future, we may want to allow loader plugins to support additional `intermediate_mappings` kinds, but that isn't relevant right now.

**Comment by RedstoneParadox** [comment]
If loader doesn't support hashed yet, shouldn't it default to intermediary?

**Comment by LoganDark** [comment]
> If loader doesn't support hashed yet, shouldn't it default to intermediary?

The point of requiring it to be set _now_ is that existing mods will add the field so that future versions can tell that they were compiled against intermediary rather than hashed. As for why not just use a default, it's not possible to choose a sane default if the field is missing because the field can also be missing on new mods.
