### ISSUE TITLE
Kotlin Support Soon?

### ISSUE THREAD

**Issue by IsaacPar** [QuiltMC/quilt-loader#64]
I'm a Kotlin coder, and i don't understand somethings on java. So... there will be Kotlin support in the future?

**Comment by gdude2002** [comment]
We have plans for Kotlin support, but they haven't been finalized yet.

**Comment by IsaacPar** [comment]
> We have plans for Kotlin support, but they haven't been finalized yet.

thanks

**Comment by IsaacPar** [comment]
That's the best staff team that I've ever seen

**Comment by P03W** [comment]
Keep in mind some basic understanding of java will still be required, as the decompiled code is java
