### ISSUE TITLE
Mod Resolution fails if a JiJ mod provides the ID of a mod present at root level

### ISSUE THREAD

**Issue by gliscowo** [QuiltMC/quilt-loader#65]
Essentially as the title says, if a mod JiJ'd in another mod declares the ID of a root-level mod in its `provides` block, mod resolution fails with the following error:
`org.quiltmc.loader.impl.discovery.ModSolvingError: <id> is already provided by ModCandidate{<providing mod>} - something has gone wrong internally!`

For a concrete example, [Numismatic Overhaul](https://modrinth.com/mod/numismatic-overhaul/version/0.1.10+1.18) and [owo-lib](https://modrinth.com/mod/owo-lib/version/0.7.0+1.18) may be used where the error will then be 
`org.quiltmc.loader.impl.discovery.ModSolvingError: owo is already provided by ModCandidate{owo-sentinel@0.5.4+1.18} - something has gone wrong internally!`. owo-sentinel here is JiJ'd in Numismatic Overhaul and is only supposed to be loaded when owo is not present to then offer the user the option to automatically download it.

**Comment by AlexIIL** [comment]
So loader really doesn't handle provides correctly then :p

thanks for the report, I'll look into it soon.

**Comment by AlexIIL** [comment]
This should now be fixed in `0.16.0-beta.11`.

**Comment by gliscowo** [comment]
From my testing it appears the issue has been resolved and sentinel loads properly now, thanks for the quick fix
I'll go ahead and close this
Cheers
