### ISSUE TITLE
[Suggestion]  A dedicated website or even a custom launcher for quilt mods?

### ISSUE THREAD

**Issue by LuciusOfLegend** [QuiltMC/quilt-loader#76]
I think there should be a website and/or custom minecraft launcher (like curse or gd) specifically for managing quilt mods (maybe including mods from other loaders, up to the team).  Let me explain how I can see this being helpful:

1. It would be difficult to be sure that quilt's goals of inclusiveness and transparency were upheld on curseforge (for example)
2. Curseforge's searching system is royally scuffed, and it would be great to have a better alternative.
3. If implemented correctly it could be very convenient for the user.  Example below :arrow_down: 

Soooo...  If you decide to make a custom launcher (please do, I would be so happy!) I have some feature ideas..  The ability to create separate modded instances along with an integrated mod installer.  The ability to create and share modpacks through the launcher.  The ability to make separate downloads for client and server branches of a modpack. (I've used "the ability" way too much now and I'm not going to edit it, I'm sorry)

That's it, hope you enjoyed my suggestion!

**Comment by OroArmor** [comment]
https://modrinth.net/

**Comment by LuciusOfLegend** [comment]
Good idea actually.  I simply didn't think of modrinth because it has far less fabric and forge mods than curseforge (I use fabric, but hope to switch to quilt someday), but now that I think of it, you can filter for quilt mods and I don't think curseforge even has quilt mods, besides which, the search system is 100 times better.

**Comment by LuciusOfLegend** [comment]
@RotatingBuffalo, now that I've heard your perspective, I agree with everything you've said (thought most of the technical stuff went over my head).  The main reason I opened this issue is because I was dissatisfied with the launchers available, and I had never heard about Theseus.  I hope too that it is a success.
