### ISSUE TITLE
Loader does not report an invalid (quilt.mod.json) entrypoint entry

### ISSUE THREAD

**Issue by P03W** [QuiltMC/quilt-loader#77]
Came across this while attempting to use a language adapter, but anything besides a `STRING` or `ARRAY` type after the entrypoint ID is silently dropped. This is notable because if you miss the ~15 words in the spec its very easy to attempt something like

```json
"entrypoints": {
  "init": {
    "adapter": "some-adapter",
    "value": "mymod.Main"
  }
}
```

which due to [these lines](https://github.com/QuiltMC/quilt-loader/blob/8ae5219d620ffffbd2594dceb943e5a4e576f621/src/main/java/org/quiltmc/loader/impl/metadata/qmj/V1ModMetadataReader.java#L605-L606) simply falls through into nothing.

**Comment by AlexIIL** [comment]
It looks like loader read the spec incorrectly - that should work AFAIK.

**Comment by AlexIIL** [comment]
This should be fixed in `0.16.1-beta.1`.

**Comment by P03W** [comment]
>It looks like loader read the spec incorrectly

yeah re-reading I misunderstood it as well 😅 

Unfortunately this doesn't seem to be fixed, my main method contains `exitProcess(1)` as an obvious "reached here" mark, and without wrapping my entrypoint in `[]` still, nothing happens

Specifically, 
```kotlin
"entrypoints": {
  "init": [{
    "adapter": "kotlin",
    "value": "io.github.p03w.transistor.Main"
  }]
},
```
invokes my main method (and closes the game with exit code 1) while
```kotlin
"entrypoints": {
  "init": {
    "adapter": "kotlin",
    "value": "io.github.p03w.transistor.Main"
  }
},
```
Just lets the game launch normally. Don't see anything in the log, just my mod listed as being loaded.

**Comment by AlexIIL** [comment]
That's odd. What happens if you remove the `value` field from the entrypoint? So:

```json
"entrypoints": {
  "init": {
    "adapter": "kotlin"
  }
},
```

**Comment by AlexIIL** [comment]
Ah sorry, I got the version wrong: try `0.16.1-beta.2` - I pushed beta.1 just before to fix an unrelated issue - can you try updating to beta.2 instead?

**Comment by P03W** [comment]
Ah yep! that runs fine, thanks much!
