### ISSUE TITLE
can't load big JiJ dependencies

### ISSUE THREAD

**Issue by wagyourtail** [QuiltMC/quilt-loader#80]
one of my users tried to load my fabric mod with quilt and ran into this issue, that I'm able to reproduce with plenty of ram.

It's only a 47.9 mb jar of `org.graalvm.js:js:22.0.0.2`.

![image](https://user-images.githubusercontent.com/6234704/168475442-d19ad4e9-a0c0-4e3e-8c42-7af6ff72487e.png)

https://paste.ee/p/RoLsS

**Comment by AlexIIL** [comment]
This should be fixed in `0.16.1-beta.3`?

**Comment by wagyourtail** [comment]
yeah, looks good! tho I'd suggest that you make it a dynamic maximum file size, maybe based on what the Xmx is. just setting it to a static 512 mb or whatever that was doesn't seem like the best choice.

**Comment by AlexIIL** [comment]
To be honest the limit was just meant to be a sanity check - and rather than imposing a strict limit, it would probably be better to just let the allocation *fail* (at least for now), and implement *not* storing large jars in-memory later.
