### ISSUE TITLE
Random Crash idk

### ISSUE THREAD

**Issue by Logboy2000** [QuiltMC/quilt-loader#81]
[latest.log](https://github.com/QuiltMC/quilt-loader/files/8697377/latest.log)

I have tried with and without fabric api but I crash either way

I do have QSL installed
https://modrinth.com/mod/qsl

**Comment by CheaterCodes** [comment]
You have a forge mod (entityculling). This is not supported by Quilt.

**Comment by TheGlitch76** [comment]
1. Install the Fabric version of [EntityCulling](https://www.curseforge.com/minecraft/mc-mods/entityculling)
2. Remove Fabric API from your mods folder

Please post the new latest.log if it still crashes.

**Comment by Logboy2000** [comment]
Sorry for taking so long but it still crashes
[latest.log](https://github.com/QuiltMC/quilt-loader/files/8749932/latest.log)
s

**Comment by Logboy2000** [comment]
help?

**Comment by CheaterCodes** [comment]
Hi, unfortunately GitHub is not designed for user support. Only a handful of people regularly check these issues, and they are busy with actually developing things.
You should have more luck with support in either our [Forum](forum.quiltmc.org) or on our [Discord](discord.quiltmc.org).

**Comment by TheGlitch76** [comment]
Yeah, please continue on the forums or Discord.
