### ISSUE TITLE
Replace shadowing night-config with implementation

### ISSUE THREAD

**Issue by teddyxlandlee** [QuiltMC/quilt-loader#84]
```groovy
shadow 'com.electronwill.night-config:core:3.6.5'
shadow 'com.electronwill.night-config:toml:3.6.5'
```
could be replace with implementation as maven dependencies

**Comment by Haven-King** [comment]
Doing so would require us to mirror NightConfig on our maven since Maven Central doesn't like end users downloading from it. That isn't a huge issue but is something I'd rather avoid.

**Comment by teddyxlandlee** [comment]
is it necessary to `provide` the loom-automated mod?  
I'm not sure what the Fabric mod id it is, but you can probably find it in Roughly Enough Items or Cloth Config

**Comment by TheGlitch76** [comment]
We intentionally don't expose night config because it is an implementation detail for our config. Exposing nightconfig would make it much harder for us to swap out backends if we wanted to/needed to.

**Comment by teddyxlandlee** [comment]
If it's an **implementation** instead, repackaging it could reduce classloading issues.

**Comment by lukebemish** [comment]
Given that the library's package is changed when loader packages it, I'm not sure what sort of classloading issues could arise from it being shadowed - do you have an example?

**Comment by teddyxlandlee** [comment]
Well, if the night-config libraries are repackaged while classloading, then this might not be an issue.

Sorry for disturbing.
