### ISSUE TITLE
`versions` array in mod metadata doesn't seem to behave properly for dependency resolution

### ISSUE THREAD

**Issue by LambdAurora** [QuiltMC/quilt-loader#91]
This has been tested with QSL 2.0.0-beta.4:

The `versions` entry has an array `[ "1.19", "1.19-alpha.22.24.a" ]`. But when the loader (version `0.17.1-beta.2`) was given Minecraft `1.18.2` and this version of QSL, it let it attempt to load.

**Comment by AlexIIL** [comment]
What file(s) are you testing with? I can't seem to find a way to download QSL 2.0.0-beta.4 from modrinth - can you link to it?

**Comment by AlexIIL** [comment]
I seem to have reproduced this with a test though, so you can ignore the request for files :p

**Comment by AlexIIL** [comment]
For some reason a blank version (like `1.19` or `1.19-alpha.22.24.a`) is getting interpreted as "SAME_MAJOR", so it only compares the `1` in `1.18.2`. I'll double-check what caused this, or if it's partially intentional?

**Comment by LambdAurora** [comment]
Reading the QMJ spec, this does not sound intentional.

**Comment by AlexIIL** [comment]
Yeah, the exact language seems to have been dropped while going from the spec -> `org.quiltmc.loader.api.VersionConstraint.Type`.

**Comment by AlexIIL** [comment]
Okay, this should be fixed in `0.17.1-beta.3`
