### ISSUE TITLE
Give a better way to figure out where Jar in Jar mods originate

### ISSUE THREAD

**Issue by Asbestosstar** [QuiltMC/quilt-loader#93]
Some mods, such as Exotic Blocks, include extra jars kind of shadowed or some other way included in there, sometimes it goes many levels deep(jar-in-jar-in-jar etc.).Sometimes these libraries bundled mods included conflict with other mods and cause problems. And yes while shadowing, fat jars and other methods to include libraries in mods is often a bad idea, it is commonly used by many mods, and it makes modpack making a pain for mods which do it. It is possible that the game could crash because of some mod you have never heard of and do not know where it is coming from. I would like a way to know which jar file the crash  is coming from and a way to know which mod a bundled mod is actually coming from.

Mod.jar -> IncludedMod.jar

An example would be if IncludedMod.jar were to crash you would be able to know that it was included in Mod.jar so you know to disable Mod.jar rather than just having the modid of the mod which failed.

**Comment by IMB11** [comment]
I'll take a look at this.

**Comment by TheGlitch76** [comment]
The mod table shows where mods were loaded from, I think that's sufficient?
