### ISSUE TITLE
Switching to Quilt but can't launch, I have no clue which mods refuse (here the log)

### ISSUE THREAD

**Issue by ardissaps** [QuiltMC/quilt-loader#94]
https://paste.atlauncher.com/view/0faee35c-42c6-4eb6-bafb-513798d5231d
![image](https://user-images.githubusercontent.com/82106625/176088130-87b47a55-681d-4bf8-8582-2b26bcd799a2.png)

**Comment by triphora** [comment]
Remove LibJF and any mods which depend on it.

This issue tracker isn't meant to be used for support; please use our [Discord](https://discord.quiltmc.org) or [Forum](https://forum.quiltmc.org) for this in the future
